import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { SupportedLanguage, SUPPORTED_LANGUAGES, LanguageOption } from '../data/i18nAuth';

export { SUPPORTED_LANGUAGES };
export type LanguageCode = SupportedLanguage;
export type { SupportedLanguage, LanguageOption };

export interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, fallback?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive dictionary for all supported languages
export const APP_TRANSLATIONS: Record<SupportedLanguage, Translations> = {
  en: {
    // Nav
    'nav.brand': 'Eden Sync',
    'nav.revival': 'Revival',
    'nav.tagline': 'Land & Water Body Restoration',
    'nav.home': 'Home',
    'nav.soilScanner': 'Soil AI Scanner',
    'nav.pollution': 'Pollution Grievances',
    'nav.customers': 'Customers DB',
    'nav.elnino': 'El Niño & Climate',
    'nav.govt': 'Govt Projects',
    'nav.register': 'Register',
    'nav.awareness': 'Awareness & Guides',
    'nav.farmerIdeas': 'Farmer Tips & Hacks',
    'nav_farmer_ideas': 'Farmer Tips',
    'nav.portal': 'Portal',
    'nav.admin': 'Admin',
    'nav.login': 'Login / Switch',
    'nav.logout': 'Logout',
    'nav.call': 'Call:',
    'nav.landowner': 'Landowner',
    'nav.adminUser': 'Admin',

    // Hero
    'hero.badge': 'Eden Sync Revival — Land & Water Body Restoration Ecosystem',
    'hero.helpline': 'Emergency Helpline:',
    'hero.title1': 'Eden Sync Revival:',
    'hero.title2': 'Land & Water Body Restoration',
    'hero.subtitle': 'Register your agricultural land, barren soil, pond, or lake for systematic eco-restoration, or file pollution complaints against illegal chemical dumping and wastewater discharge. We connect landowners and communities with AI-guided soil/water triage, ecological experts, and government restoration programs.',
    'hero.btnRegister': 'Register Land / Water Body',
    'hero.btnReportPollution': 'Report Pollution (Land/Water)',
    'hero.btnGovt': 'Govt Restoration',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'Acres Restored',
    'hero.stat1Sub': 'Organic carbon & pH balanced',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'Water Bodies Revived',
    'hero.stat2Sub': 'Desilted & groundwater recharged',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'Pollution Reports Resolved',
    'hero.stat3Sub': 'Industrial & chemical triage',
    'hero.stat4Val': '₹48.2 Cr',
    'hero.stat4Title': 'Govt Funds Facilitated',
    'hero.stat4Sub': 'Direct ecological subsidies',

    // Home Features
    'home.pillarsTitle': 'Restoration Pillars & Grievance Redressal',
    'home.pillarsHeader': 'Eden Sync Revival: Land & Water Body Restoration Ecosystem',
    'home.pillarsSub': 'A seamless digital bridge uniting landowner restoration registrations, pollution complaint triage, verified customer requirements, real-time climate shift awareness, and government ecological restoration funds.',
    'home.soilCardTitle': 'Soil AI Photo Scanner',
    'home.soilCardBadge': 'Dry • Clay • Healthy • Heavy',
    'home.soilCardDesc': 'Snap or upload a photo of your field soil. AI detects whether it\'s Dry, Clay, Healthy, or Heavy, estimates moisture %, and delivers immediate agronomic advice.',
    'home.soilCardBtn': 'Scan Soil Photo Now',
    'home.pollCardTitle': 'Land & Water Pollution Grievances',
    'home.pollCardBadge': 'AI Triage Active',
    'home.pollCardDesc': 'Report toxic chemical dumping, industrial effluents, illegal plastic dumping, and sewage discharge. Get immediate AI hazard containment and bio-remediation protocols.',
    'home.pollCardBtn': 'File or Track Grievance',
    'home.custCardTitle': 'Customer Database',
    'home.custCardBadge': 'Admin Only',
    'home.custCardDesc': 'Secure directory of landowner profiles, specific soil health diagnostics (pH, carbon), budget preferences, and AI restoration blueprints.',
    'home.custCardBtn': 'View Customer DB',
    'home.custCardBtnLogin': 'Admin Login to View',
    'home.elninoCardTitle': 'El Niño & Climate Shift',
    'home.elninoCardDesc': 'Live ENSO telemetry, global regional temperature/rainfall anomalies, interactive farm vulnerability simulator, and nature-based adaptation guides.',
    'home.elninoCardBtn': 'Explore Climate Hub',
    'home.agriCardTitle': 'Agricultural Land Revival',
    'home.agriCardDesc': 'Register degraded, saline, or barren land for comprehensive soil testing, organic enrichment, bio-mulching, and high-carbon crop rotation.',
    'home.agriCardBtn': 'Register Your Land',
    'home.waterCardTitle': 'Water Body Rejuvenation',
    'home.waterCardDesc': 'Eco-dredging, floating vetiver wetlands, catchment swales, and interactive satellite mapping tracking live government restoration milestones.',
    'home.waterCardBtn': 'View Govt Projects',
    'home.guideCardTitle': 'Science & Policy Guides',
    'home.guideCardDesc': '20 Natural fertilizer making recipes, best practices for desilting, rainwater harvesting bunds, saline soil reclamation, and legal frameworks.',
    'home.guideCardBtn': 'Read Knowledge Hub',
    'home.helpBannerTitle': 'Need Immediate Assistance?',
    'home.helpBannerSub': 'Direct Landowner Support & Emergency Pollution Helpline',
    'home.helpBannerDesc': 'Our ecological restoration field officers and environmental triage team are available to help you with land registration, soil testing reports, pollution incidents, or government project status.',

    // Awareness
    'aware.badge': 'Eden Sync Ecological Knowledge & Farmer Empowerment Hub',
    'aware.title': 'The Science & Practice of Soil, Water & Living Agroecology',
    'aware.subtitle': 'Practical, field-tested intelligence for landowners, smallholder farmers, and conservationists. Discover 20 natural fertilizer formulations, community tank de-silting, soil organic carbon replenishment, and rainwater catchment engineering.',
    'aware.tabGuides': 'Illustrated Guides',
    'aware.tabRecipes': '20 Natural Fertilizer Recipes',
    'aware.tabCalc': 'Eco Calculators & Sizers',
    'aware.tabMyths': 'Myth vs Science',
    'aware.tabBiofence': 'Bio-Fence Blueprints',
    'aware.smallFarmerBadge': 'Tailored for New & Smallholder Farmers (0.5 to 3 Acres)',
    'aware.allCategories': 'All Categories',
    'aware.searchPlaceholder': 'Search fertilizer recipes, biochar, pest repellents...',
    'aware.prepTime': 'Prep Time',
    'aware.shelfLife': 'Shelf Life',
    'aware.dilution': 'Dilution Rate',
    'aware.costEst': 'Estimated Cost',
    'aware.viewRecipeBtn': 'View Step-by-Step Preparation Guide',
    'aware.ingredientsRequired': 'Core Ingredients Required',
    'aware.stepByStep': 'Step-by-Step Preparation Method',
    'aware.keyBenefits': 'Key Agronomic Benefits for Smallholder Farmers',
    'aware.precautions': 'Important Precautions & Handling',

    // Soil Scanner
    'soil.scannerTitle': 'Soil & Water AI Photo Detector',
    'soil.scannerSub': 'Upload or capture a photo of your field soil or local water body to get instant AI condition classification, moisture analysis, and tailored ecological remediation steps.',
    'soil.tabSoil': '🌱 Soil Photo Detector',
    'soil.tabWater': '💧 Water Body Detector',
    'soil.uploadTitle': 'Upload Soil Sample Image',
    'soil.uploadSub': 'Supports JPG, PNG, WEBP. For best results, capture in natural daylight.',
    'soil.btnScan': 'Analyze Sample with AI',
    'soil.healthIndex': 'Soil Health Index',
    'soil.moistureLevel': 'Moisture Level',
    'soil.organicMatter': 'Organic Matter',
    'soil.recommendations': 'Immediate Action Plan',

    // Pollution
    'poll.title': 'Land & Water Pollution Grievance Portal',
    'poll.sub': 'Report industrial dumping, illegal sewage, chemical effluents, or plastic hazards. AI automatically generates instant hazard triage, ecological risk score, and notification to responsible authorities.',
    'poll.btnFile': 'File New Pollution Grievance',
    'poll.btnTrack': 'Track Existing Grievance',
    'poll.domainLand': 'Land & Soil Pollution',
    'poll.domainWater': 'Water Body & River Pollution',

    // Footer
    'footer.brand': 'Eden Sync Revival',
    'footer.sub': 'Land & Water Body Restoration Platform',
    'footer.helplineLabel': 'Helpline & Pollution Incident Line:',
    'footer.quote': '"Restoring Earth, Syncing Lives with Nature."',
    'footer.copyright': '© 2026 Eden Sync Revival. Land & Water Restoration Network.',
  },
  ta: {
    // Nav
    'nav.brand': 'ஈடன் சிங்க்',
    'nav.revival': 'புத்துயிர்',
    'nav.tagline': 'நிலம் மற்றும் நீர்நிலைகள் மறுசீரமைப்பு',
    'nav.home': 'முகப்பு',
    'nav.soilScanner': 'மண் AI ஸ்கேனர்',
    'nav.pollution': 'மாசுபாட்டுக் குறைகள்',
    'nav.customers': 'வாடிக்கையாளர் பட்டியல்',
    'nav.elnino': 'எல் நினோ & தட்பவெப்பநிலை',
    'nav.govt': 'அரசு திட்டங்கள்',
    'nav.register': 'பதிவு செய்க',
    'nav.awareness': 'விழிப்புணர்வு & வழிகாட்டிகள்',
    'nav.portal': 'போர்டல்',
    'nav.admin': 'நிர்வாகி',
    'nav.login': 'உள்நுழைவு / மாற்று',
    'nav.logout': 'வெளியேறு',
    'nav.call': 'அழைக்க:',
    'nav.landowner': 'நில உரிமையாளர்',
    'nav.adminUser': 'நிர்வாகி',

    // Hero
    'hero.badge': 'ஈடன் சிங்க் புத்துயிர் — நிலம் மற்றும் நீர்நிலைகள் மீட்பு சுற்றுச்சூழல்',
    'hero.helpline': 'அவசர உதவி எண்:',
    'hero.title1': 'ஈடன் சிங்க் புத்துயிர்:',
    'hero.title2': 'நிலம் & நீர்நிலைகள் மறுசீரமைப்பு',
    'hero.subtitle': 'உங்கள் விவசாய நிலம், தரிசு நிலம், குளம் அல்லது ஏரியை மறுசீரமைக்க பதிவு செய்யுங்கள் அல்லது ரசாயனக் கழிவுகள் மற்றும் கழிவுநீர் வெளியேற்றத்திற்கு எதிராக புகார் அளியுங்கள். AI வழிகாட்டுதலுடன் கூடிய மண்/நீர் பகுப்பாய்வு, இயற்கை வேளாண் வல்லுநர்கள் மற்றும் அரசு திட்டங்களை நாங்கள் உங்களுக்கு இணைக்கிறோம்.',
    'hero.btnRegister': 'நிலம் / நீர்நிலையை பதிவு செய்க',
    'hero.btnReportPollution': 'மாசுபாட்டைப் புகாரளிக்கவும் (நிலம்/நீர்)',
    'hero.btnGovt': 'அரசு மறுசீரமைப்புத் திட்டங்கள்',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'ஏக்கர் நிலம் மீட்பு',
    'hero.stat1Sub': 'கரிம கார்பன் & காரத்தன்மை சமநிலை',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'நீர்நிலைகள் தூர்வாரப்பட்டன',
    'hero.stat2Sub': 'நிலத்தடி நீர் மட்டம் அதிகரிப்பு',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'மாசுபாட்டுப் புகார்கள் தீர்வு',
    'hero.stat3Sub': 'தொழிலக கழிவு மீட்பு',
    'hero.stat4Val': '₹48.2 கோடி',
    'hero.stat4Title': 'அரசு மானியங்கள் & நிதி',
    'hero.stat4Sub': 'நேரடி மறுசீரமைப்பு நிதி உதவி',

    // Home Features
    'home.pillarsTitle': 'மறுசீரமைப்பு தூண்கள் & குறைதீர்ப்பு',
    'home.pillarsHeader': 'ஈடன் சிங்க் புத்துயிர்: நிலம் & நீர்நிலை மீட்பு சூழலமைப்பு',
    'home.pillarsSub': 'நில உரிமையாளர் பதிவு, மாசு புகார் தீர்வு, வாடிக்கையாளர் தேவை, காலநிலை விழிப்புணர்வு மற்றும் அரசு மறுசீரமைப்பு நிதியை இணைக்கும் ஒருங்கிணைந்த தளம்.',
    'home.soilCardTitle': 'மண் AI புகைப்பட ஸ்கேனர்',
    'home.soilCardBadge': 'வறண்ட • களிமண் • வளமான • ஈரப்பத மண்',
    'home.soilCardDesc': 'உங்கள் நிலத்தின் மண் புகைப்படத்தை எடுத்து அல்லது பதிவேற்றி உடனடியாக மண் வகை, ஈரப்பதம் % மற்றும் இயற்கை உர ஆலோசனைகளைப் பெறுங்கள்.',
    'home.soilCardBtn': 'மண் புகைப்படத்தை ஸ்கேன் செய்க',
    'home.pollCardTitle': 'நிலம் & நீர் மாசுபாட்டுக் குறைகள்',
    'home.pollCardBadge': 'AI உடனடி தீர்வு இயங்குகிறது',
    'home.pollCardDesc': 'விவசாய நிலத்தில் ரசாயனக் கழிவு கொட்டுதல், தொழிற்சாலை கழிவுநீர், பிளாஸ்டிக் கழிவுகளைப் புகாரளித்து உடனடி AI பாதுகாப்பு வழிமுறைகளைப் பெறுங்கள்.',
    'home.pollCardBtn': 'புகார் பதிவு / கண்காணிக்க',
    'home.custCardTitle': 'வாடிக்கையாளர் தரவுத்தளம்',
    'home.custCardBadge': 'நிர்வாகி மட்டும்',
    'home.custCardDesc': 'விவசாயிகள் மற்றும் நில உரிமையாளர்களின் மண் ஆரோக்கியம், காரத்தன்மை, பட்ஜெட் மற்றும் மறுசீரமைப்பு திட்டங்களின் பட்டியல்.',
    'home.custCardBtn': 'வாடிக்கையாளர் பட்டியலை பார்க்க',
    'home.custCardBtnLogin': 'பார்க்க நிர்வாகி உள்நுழையவும்',
    'home.elninoCardTitle': 'எல் நினோ & காலநிலை மாற்றம்',
    'home.elninoCardDesc': 'நேரலை ENSO தகவல்கள், வெப்பநிலை மாற்றங்கள், பண்ணை பாதிப்பு கணக்கீடு மற்றும் வறட்சி தாங்கும் இயற்கை விவசாய முறைகள்.',
    'home.elninoCardBtn': 'காலநிலை மையத்தை ஆராய்க',
    'home.agriCardTitle': 'விவசாய நிலம் புத்துயிரூட்டல்',
    'home.agriCardDesc': 'களர், உவர் அல்லது தரிசு நிலங்களை முழுமையான மண் பரிசோதனை, பசுந்தாள் உரம், உயிர் மூடாக்கு மற்றும் இயற்கை சாகுபடிக்கு பதிவு செய்க.',
    'home.agriCardBtn': 'உங்கள் நிலத்தை பதிவு செய்க',
    'home.waterCardTitle': 'நீர்நிலைகள் புத்துயிர்',
    'home.waterCardDesc': 'குளம் தூர்வாருதல், வெட்டிவேர் மிதக்கும் தீவுகள், மழைநீர் சேகரிப்பு வரப்புகள் மற்றும் அரசு நிதி கண்காணிப்பு.',
    'home.waterCardBtn': 'அரசு திட்டங்களை பார்க்க',
    'home.guideCardTitle': 'அறிவியல் & இயற்கை உர வழிகாட்டிகள்',
    'home.guideCardDesc': '20 இயற்கை உரம் தயாரிக்கும் முறைகள், தூர்வாருதல் நுட்பங்கள், மழைநீர் சேகரிப்பு மற்றும் களர் நில சீர்திருத்தங்கள்.',
    'home.guideCardBtn': 'விழிப்புணர்வு மையத்தை படிக்க',
    'home.helpBannerTitle': 'உடனடி உதவி தேவையா?',
    'home.helpBannerSub': 'விவசாயிகள் நேரடி உதவி & அவசர மாசு கட்டுப்பாட்டு உதவி எண்',
    'home.helpBannerDesc': 'நிலப் பதிவு, மண் பரிசோதனை அறிக்கைகள், சுற்றுச்சூழல் மாசு பிரச்சினைகள் அல்லது அரசு திட்ட நிலவரம் குறித்து எங்கள் வல்லுநர்களை உடனடியாகத் தொடர்பு கொள்ளலாம்.',

    // Awareness
    'aware.badge': 'ஈடன் சிங்க் சுற்றுச்சூழல் அறிவு & உழவர் மேம்பாட்டு மையம்',
    'aware.title': 'மண், நீர் மற்றும் இயற்கை வேளாண்மையின் அறிவியல்',
    'aware.subtitle': 'சிறிய மற்றும் புதிய விவசாயிகளுக்கான 20 இயற்கை உரம் தயாரிக்கும் முறைகள், குளங்கள் தூர்வாருதல், மண்ணின் கரிம கார்பன் உயர்த்துதல் மற்றும் மழைநீர் சேகரிப்பு வழிகாட்டிகள்.',
    'aware.tabGuides': 'விளக்க வழிகாட்டிகள்',
    'aware.tabRecipes': '20 இயற்கை உரம் தயாரிக்கும் முறைகள்',
    'aware.tabCalc': 'சுற்றுச்சூழல் கால்குலேட்டர்கள்',
    'aware.tabMyths': 'மாயை vs அறிவியல் உண்மை',
    'aware.tabBiofence': 'உயிர் வேலி வரைபடங்கள்',
    'aware.smallFarmerBadge': 'புதிய மற்றும் சிறு/குறு விவசாயிகளுக்கு ஏற்றது (0.5 - 3 ஏக்கர்)',
    'aware.allCategories': 'அனைத்து பிரிவுகள்',
    'aware.searchPlaceholder': 'இயற்கை உரம், பூச்சி விரட்டி, ஜீவாமிர்தம் தேட...',
    'aware.prepTime': 'தயாரிப்பு நேரம்',
    'aware.shelfLife': 'பயன்படுத்தும் காலம்',
    'aware.dilution': 'கலக்கும் விகிதம்',
    'aware.costEst': 'தோராய செலவு',
    'aware.viewRecipeBtn': 'படிபடியான தயாரிப்பு முறையைப் பார்க்க',
    'aware.ingredientsRequired': 'தேவையான முக்கிய பொருட்கள்',
    'aware.stepByStep': 'படிபடியான செய்முறை விளக்கம்',
    'aware.keyBenefits': 'சிறு விவசாயிகளுக்கான முக்கிய நன்மைகள்',
    'aware.precautions': 'முக்கிய முன்னெச்சரிக்கைகள்',

    // Soil Scanner
    'soil.scannerTitle': 'மண் மற்றும் நீர் AI புகைப்பட ஸ்கேனர்',
    'soil.scannerSub': 'உங்கள் நிலத்தின் மண் அல்லது நீர்நிலையின் புகைப்படத்தை பதிவேற்றி உடனடி AI வகைப்பாடு, ஈரப்பதம் மற்றும் இயற்கை மேலாண்மை வழிமுறைகளைப் பெறுங்கள்.',
    'soil.tabSoil': '🌱 மண் புகைப்பட ஸ்கேனர்',
    'soil.tabWater': '💧 நீர்நிலை ஸ்கேனர்',
    'soil.uploadTitle': 'மண் மாதிரி புகைப்படத்தைப் பதிவேற்றவும்',
    'soil.uploadSub': 'JPG, PNG, WEBP ஆதரிக்கப்படுகிறது. இயற்கை வெளிச்சத்தில் புகைப்படம் எடுக்கவும்.',
    'soil.btnScan': 'AI மூலம் மாதிரியைப் பகுப்பாய்வு செய்க',
    'soil.healthIndex': 'மண் ஆரோக்கிய குறியீடு',
    'soil.moistureLevel': 'ஈரப்பத அளவு',
    'soil.organicMatter': 'கரிமப் பொருள்',
    'soil.recommendations': 'உடனடி செயல் திட்டம்',

    // Pollution
    'poll.title': 'நிலம் & நீர் மாசுபாடு குறைதீர்ப்பு போர்டல்',
    'poll.sub': 'தொழிற்சாலை கழிவுகள் கொட்டுதல், கழிவுநீர் வெளியேற்றம் அல்லது பிளாஸ்டிக் மாசுபாட்டைப் பதிவு செய்து உடனடி AI தடுப்பு வழிகாட்டலைப் பெறுங்கள்.',
    'poll.btnFile': 'புதிய மாசு புகாரைப் பதிவு செய்க',
    'poll.btnTrack': 'புகார் நிலவரத்தை கண்காணிக்க',
    'poll.domainLand': 'நிலம் மற்றும் மண் மாசுபாடு',
    'poll.domainWater': 'நீர்நிலை மற்றும் ஆறு மாசுபாடு',

    // Footer
    'footer.brand': 'ஈடன் சிங்க் புத்துயிர்',
    'footer.sub': 'நிலம் மற்றும் நீர்நிலைகள் மறுசீரமைப்பு தளம்',
    'footer.helplineLabel': 'உதவி எண் & மாசு சம்பவ அழைப்பு எண்:',
    'footer.quote': '"பூமியை மீட்டெடுப்போம், இயற்கையோடு வாழ்வை இணைப்போம்."',
    'footer.copyright': '© 2026 ஈடன் சிங்க் புத்துயிர். நிலம் & நீர் மறுசீரமைப்பு நெட்வொர்க்.',
  },
  hi: {
    // Nav
    'nav.brand': 'ईडन सिंक',
    'nav.revival': 'पुनरुद्धार',
    'nav.tagline': 'भूमि एवं जल निकाय पुनरुद्धार',
    'nav.home': 'होम',
    'nav.soilScanner': 'मृदा AI स्कैनर',
    'nav.pollution': 'प्रदूषण शिकायतें',
    'nav.customers': 'ग्राहक डेटाबेस',
    'nav.elnino': 'अल नीनो एवं जलवायु',
    'nav.govt': 'सरकारी परियोजनाएं',
    'nav.register': 'पंजीकरण',
    'nav.awareness': 'जागरूकता एवं गाइड',
    'nav.portal': 'पोर्टल',
    'nav.admin': 'प्रशासक',
    'nav.login': 'लॉगिन / बदलें',
    'nav.logout': 'लॉग आउट',
    'nav.call': 'कॉल करें:',
    'nav.landowner': 'जमीन मालिक',
    'nav.adminUser': 'व्यवस्थापक',

    // Hero
    'hero.badge': 'ईडन सिंक रिवाइवल — भूमि एवं जल निकाय पुनरुद्धार पारिस्थितिकी',
    'hero.helpline': 'आपातकालीन हेल्पलाइन:',
    'hero.title1': 'ईडन सिंक रिवाइवल:',
    'hero.title2': 'भूमि एवं जल निकाय पुनरुद्धार',
    'hero.subtitle': 'अपनी कृषि भूमि, बंजर मिट्टी, तालाब या झील के व्यवस्थित पर्यावरण पुनरुद्धार के लिए पंजीकरण करें, या अवैध रासायनिक डंपिंग के खिलाफ शिकायत दर्ज करें। हम भूमि स्वामियों को AI मृदा परीक्षण, विशेषज्ञ परामर्श और सरकारी योजनाओं से जोड़ते हैं।',
    'hero.btnRegister': 'भूमि / जल निकाय पंजीकृत करें',
    'hero.btnReportPollution': 'प्रदूषण की शिकायत करें (भूमि/जल)',
    'hero.btnGovt': 'सरकारी बहाली योजनाएं',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'एकड़ भूमि बहाल',
    'hero.stat1Sub': 'जैविक कार्बन और pH संतुलित',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'जल निकाय पुनर्जीवित',
    'hero.stat2Sub': 'गाद निकाली और भूजल रीचार्ज',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'प्रदूषण शिकायतें हल',
    'hero.stat3Sub': 'औद्योगिक अपशिष्ट समाधान',
    'hero.stat4Val': '₹48.2 करोड़',
    'hero.stat4Title': 'सरकारी फंड सुविधा',
    'hero.stat4Sub': 'प्रत्यक्ष बहाली सब्सिडी',

    // Home Features
    'home.pillarsTitle': 'पुनरुद्धार स्तंभ एवं शिकायत निवारण',
    'home.pillarsHeader': 'ईडन सिंक रिवाइवल: भूमि एवं जल निकाय पुनरुद्धार ईकोसिस्टम',
    'home.pillarsSub': 'भूमि स्वामी पंजीकरण, प्रदूषण शिकायत निवारण, सत्यापित ग्राहक आवश्यकताएं, वास्तविक समय जलवायु जागरूकता और सरकारी पर्यावरण पुनरुद्धार फंड का डिजिटल संगम।',
    'home.soilCardTitle': 'मृदा AI फोटो स्कैनर',
    'home.soilCardBadge': 'शुष्क • चिकनी मिट्टी • उपजाऊ • भारी मिट्टी',
    'home.soilCardDesc': 'अपने खेत की मिट्टी की फोटो लें या अपलोड करें। AI तुरंत पता लगाएगा कि मिट्टी कैसी है, नमी % क्या है, और तुरंत प्राकृतिक उर्वरक सलाह देगा।',
    'home.soilCardBtn': 'मिट्टी की फोटो स्कैन करें',
    'home.pollCardTitle': 'भूमि एवं जल प्रदूषण शिकायतें',
    'home.pollCardBadge': 'AI त्वरित समाधान सक्रिय',
    'home.pollCardDesc': 'रासायनिक कचरा डंपिंग, औद्योगिक अपशिष्ट, प्लास्टिक कचरा और सीवेज बहाव की रिपोर्ट करें और तुरंत AI रोकथाम सलाह पाएं।',
    'home.pollCardBtn': 'शिकायत दर्ज या ट्रैक करें',
    'home.custCardTitle': 'ग्राहक डेटाबेस',
    'home.custCardBadge': 'केवल व्यवस्थापक',
    'home.custCardDesc': 'भूमि स्वामियों की मृदा स्वास्थ्य प्रोफाइल, pH, जैविक कार्बन और बहाली योजनाओं की सुरक्षित निर्देशिका।',
    'home.custCardBtn': 'ग्राहक डेटाबेस देखें',
    'home.custCardBtnLogin': 'देखने के लिए एडमिन लॉगिन करें',
    'home.elninoCardTitle': 'अल नीनो एवं जलवायु परिवर्तन',
    'home.elninoCardDesc': 'लाइव ENSO डेटा, क्षेत्रीय तापमान/वर्षा बदलाव, इंटरएक्टिव खेत संवेदनशीलता सिमुलेटर और सूखा अनुकूलन गाइड।',
    'home.elninoCardBtn': 'जलवायु केंद्र देखें',
    'home.agriCardTitle': 'कृषि भूमि पुनरुद्धार',
    'home.agriCardDesc': 'खराब, लवणीय या बंजर भूमि को संपूर्ण मृदा परीक्षण, जैविक खाद संवर्धन, बायो-मल्चिंग और फसल चक्र के लिए पंजीकृत करें।',
    'home.agriCardBtn': 'अपनी भूमि पंजीकृत करें',
    'home.waterCardTitle': 'जल निकाय का कायाकल्प',
    'home.waterCardDesc': 'तालाब से गाद हटाना, तैरते हुए वेटलैंड्स, वर्षा जल संचयन और लाइव सरकारी बहाली मील के पत्थर।',
    'home.waterCardBtn': 'सरकारी परियोजनाएं देखें',
    'home.guideCardTitle': 'विज्ञान एवं प्राकृतिक खाद गाइड',
    'home.guideCardDesc': '20 प्राकृतिक उर्वरक बनाने की विधियां, गाद निकालने की तकनीक, वर्षा जल संचयन और लवणीय भूमि सुधार।',
    'home.guideCardBtn': 'ज्ञान केंद्र पढ़ें',
    'home.helpBannerTitle': 'क्या आपको तत्काल सहायता चाहिए?',
    'home.helpBannerSub': 'भूमि स्वामी सहायता एवं आपातकालीन प्रदूषण हेल्पलाइन',
    'home.helpBannerDesc': 'हमारे पर्यावरण बहाली अधिकारी और तकनीकी टीम भूमि पंजीकरण, मृदा परीक्षण रिपोर्ट, प्रदूषण समस्याओं या सरकारी योजनाओं की स्थिति में आपकी सहायता के लिए तैयार हैं।',

    // Awareness
    'aware.badge': 'ईडन सिंक पारिस्थितिक ज्ञान एवं किसान सशक्तिकरण केंद्र',
    'aware.title': 'मिट्टी, जल एवं प्राकृतिक कृषि का विज्ञान',
    'aware.subtitle': 'छोटे एवं नए किसानों के लिए 20 प्राकृतिक उर्वरक बनाने की विधियां, तालाब गाद निकालना, जैविक कार्बन बढ़ाना और वर्षा जल संचयन इंजीनियरिंग।',
    'aware.tabGuides': 'सचित्र गाइड',
    'aware.tabRecipes': '20 प्राकृतिक उर्वरक निर्माण विधियां',
    'aware.tabCalc': 'पारिस्थितिक कैलकुलेटर',
    'aware.tabMyths': 'भ्रांति बनाम विज्ञान',
    'aware.tabBiofence': 'जैव बाड़ (Bio-Fence) योजनाएं',
    'aware.smallFarmerBadge': 'नए और छोटे किसानों के लिए विशेष (0.5 से 3 एकड़)',
    'aware.allCategories': 'सभी श्रेणियां',
    'aware.searchPlaceholder': 'उर्वरक विधि, जीवामृत, कीट विकर्षक खोजें...',
    'aware.prepTime': 'बनाने का समय',
    'aware.shelfLife': 'उपयोग अवधि',
    'aware.dilution': 'घोल का अनुपात',
    'aware.costEst': 'अनुमानित लागत',
    'aware.viewRecipeBtn': 'चरण-दर-चरण निर्माण विधि देखें',
    'aware.ingredientsRequired': 'आवश्यक प्रमुख सामग्रियां',
    'aware.stepByStep': 'चरण-दर-चरण तैयारी विधि',
    'aware.keyBenefits': 'छोटे किसानों के लिए प्रमुख लाभ',
    'aware.precautions': 'महत्वपूर्ण सावधानियां',

    // Soil Scanner
    'soil.scannerTitle': 'मृदा एवं जल AI फोटो डिटेक्टर',
    'soil.scannerSub': 'अपने खेत की मिट्टी या स्थानीय जल निकाय की फोटो अपलोड करें और तुरंत AI स्थिति वर्गीकरण, नमी विश्लेषण और प्राकृतिक समाधान प्राप्त करें।',
    'soil.tabSoil': '🌱 मृदा फोटो डिटेक्टर',
    'soil.tabWater': '💧 जल निकाय डिटेक्टर',
    'soil.uploadTitle': 'मृदा नमूना फोटो अपलोड करें',
    'soil.uploadSub': 'JPG, PNG, WEBP समर्थित। प्राकृतिक दिन के उजाले में फोटो लें।',
    'soil.btnScan': 'AI द्वारा नमूने का विश्लेषण करें',
    'soil.healthIndex': 'मृदा स्वास्थ्य सूचकांक',
    'soil.moistureLevel': 'नमी का स्तर',
    'soil.organicMatter': 'जैविक पदार्थ',
    'soil.recommendations': 'तत्काल कार्य योजना',

    // Pollution
    'poll.title': 'भूमि एवं जल प्रदूषण शिकायत पोर्टल',
    'poll.sub': 'औद्योगिक अपशिष्ट डंपिंग, अवैध सीवेज या रासायनिक प्रदूषण की रिपोर्ट करें। AI तुरंत जोखिम विश्लेषण और अधिकारियों को सूचना तैयार करेगा।',
    'poll.btnFile': 'नई प्रदूषण शिकायत दर्ज करें',
    'poll.btnTrack': 'शिकायत की स्थिति ट्रैक करें',
    'poll.domainLand': 'भूमि एवं मृदा प्रदूषण',
    'poll.domainWater': 'जल निकाय एवं नदी प्रदूषण',

    // Footer
    'footer.brand': 'ईडन सिंक रिवाइवल',
    'footer.sub': 'भूमि एवं जल निकाय पुनरुद्धार मंच',
    'footer.helplineLabel': 'हेल्पलाइन एवं प्रदूषण रिपोर्ट नंबर:',
    'footer.quote': '"पृथ्वी को बहाल करें, प्रकृति के साथ जीवन जोड़ें।"',
    'footer.copyright': '© 2026 ईडन सिंक रिवाइवल। भूमि एवं जल पुनरुद्धार नेटवर्क।',
  },
  te: {
    // Nav
    'nav.brand': 'ఈడెన్ సింక్',
    'nav.revival': 'పునరుద్ధరణ',
    'nav.tagline': 'భూమి & జలాశయాల పునరుజ్జీవనం',
    'nav.home': 'హోమ్',
    'nav.soilScanner': 'నేల AI స్కానర్',
    'nav.pollution': 'కాలుష్య ఫిర్యాదులు',
    'nav.customers': 'కస్టమర్ల డేటాబేస్',
    'nav.elnino': 'ఎల్ నినో & వాతావరణం',
    'nav.govt': 'ప్రభుత్వ ప్రాజెక్టులు',
    'nav.register': 'రిజిస్టర్',
    'nav.awareness': 'అవగాహన & గైడ్లు',
    'nav.portal': 'పోర్టల్',
    'nav.admin': 'అడ్మిన్',
    'nav.login': 'లాగిన్ / మార్చు',
    'nav.logout': 'లాగౌట్',
    'nav.call': 'కాల్ చేయండి:',
    'nav.landowner': 'భూ యజమాని',
    'nav.adminUser': 'అడ్మిన్',

    // Hero
    'hero.badge': 'ఈడెన్ సింక్ పునరుద్ధరణ — భూమి మరియు జలాశయాల పునరుజ్జీవనం',
    'hero.helpline': 'అత్యవసర హెల్ప్‌లైన్:',
    'hero.title1': 'ఈడెన్ సింక్ పునరుద్ధరణ:',
    'hero.title2': 'భూమి & జలాశయాల పునరుజ్జీవనం',
    'hero.subtitle': 'మీ వ్యవసాయ భూమి, బంజరు నేల, చెరువు లేదా సరస్సును పునరుజ్జీవింపజేయడానికి నమోదు చేసుకోండి లేదా కాలుష్య ఫిర్యాదులు చేయండి. మేము రైతులకు AI పరీక్షలు, నిపుణుల సలహాలు మరియు ప్రభుత్వ పథకాలను అనుసంధానిస్తాము.',
    'hero.btnRegister': 'భూమి / జలాశయాన్ని నమోదు చేయండి',
    'hero.btnReportPollution': 'కాలుష్యంపై ఫిర్యాదు చేయండి',
    'hero.btnGovt': 'ప్రభుత్వ పథకాలు',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'ఎకరాల భూమి పునరుద్ధరణ',
    'hero.stat1Sub': 'సేంద్రీయ కార్బన్ సమతుల్యత',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'చెరువులు పూడికతీత',
    'hero.stat2Sub': 'భూగర్భ జలాలు రీఛార్జ్',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'కాలుష్య సమస్యల పరిష్కారం',
    'hero.stat3Sub': 'రసాయన వ్యర్థాల నిర్మూలన',
    'hero.stat4Val': '₹48.2 కోట్లు',
    'hero.stat4Title': 'ప్రభుత్వ సబ్సిడీలు',
    'hero.stat4Sub': 'రైతులకు ప్రత్యక్ష సహాయం',

    // Home Features
    'home.pillarsTitle': 'పునరుద్ధరణ స్తంభాలు & పరిష్కారాలు',
    'home.pillarsHeader': 'ఈడెన్ సింక్: సమగ్ర భూమి & నీటి సంరక్షణ వ్యవస్థ',
    'home.pillarsSub': 'రైతుల నమోదు, కాలుష్య నివారణ, వాతావరణ హెచ్చరికలు మరియు ప్రభుత్వ నిధులను ఒకే వేదికపైకి తెచ్చే సాంకేతికత.',
    'home.soilCardTitle': 'నేల AI ఫోటో స్కానర్',
    'home.soilCardBadge': 'ఎండిన • బంకమట్టి • సారవంతమైన • తేమ నేల',
    'home.soilCardDesc': 'మీ పొలం మట్టి ఫోటో తీసి అప్‌లోడ్ చేయండి. AI క్షణాల్లో నేల స్వభావం, తేమ % లెక్కించి సహజ ఎరువుల సలహాలను ఇస్తుంది.',
    'home.soilCardBtn': 'మట్టి ఫోటో స్కాన్ చేయండి',
    'home.pollCardTitle': 'భూమి & నీటి కాలుష్య ఫిర్యాదులు',
    'home.pollCardBadge': 'AI తక్షణ పరిష్కారం',
    'home.pollCardDesc': 'రసాయన వ్యర్థాలు, ప్లాస్టిక్ లేదా డ్రైనేజీ నీటి డంపింగ్‌పై ఫిర్యాదు చేసి తక్షణ పరిష్కార చర్యలు పొందండి.',
    'home.pollCardBtn': 'ఫిర్యాదు చేయండి / ట్రాక్ చేయండి',
    'home.custCardTitle': 'కస్టమర్ల డేటాబేస్',
    'home.custCardBadge': 'అడ్మిన్ మాత్రమే',
    'home.custCardDesc': 'రైతుల నేల ఆరోగ్యం, pH, కార్బన్ మరియు పునరుద్ధరణ బ్లూప్రింట్ల సమాచారం.',
    'home.custCardBtn': 'కస్టమర్ల జాబితా చూడండి',
    'home.custCardBtnLogin': 'చూడటానికి అడ్మిన్ లాగిన్ చేయండి',
    'home.elninoCardTitle': 'ఎల్ నినో & వాతావరణ మార్పు',
    'home.elninoCardDesc': 'ఉష్ణోగ్రత మార్పులు, వర్షపాతం అంచనాలు మరియు కరువును తట్టుకునే సహజ సాగు పద్ధతులు.',
    'home.elninoCardBtn': 'వాతావరణ కేంద్రం చూడండి',
    'home.agriCardTitle': 'వ్యవసాయ భూమి పునరుజ్జీవనం',
    'home.agriCardDesc': 'చౌడు లేదా బంజరు భూములను పచ్చిరొట్ట ఎరువులు, సహజ మల్చింగ్ ద్వారా సారవంతం చేసుకోండి.',
    'home.agriCardBtn': 'మీ భూమిని నమోదు చేయండి',
    'home.waterCardTitle': 'జలాశయాల పునరుద్ధరణ',
    'home.waterCardDesc': 'చెరువుల పూడికతీత, వెటివర్ గడ్డి పెంపకం, వర్షపు నీటి నిల్వ పనులు.',
    'home.waterCardBtn': 'ప్రభుత్వ ప్రాజెక్టులు చూడండి',
    'home.guideCardTitle': 'సైన్స్ & సహజ ఎరువుల గైడ్లు',
    'home.guideCardDesc': '20 రకాల సహజ ఎరువుల తయారీ విధానాలు, పూడికతీత మరియు కాలుష్య నివారణ చట్టాలు.',
    'home.guideCardBtn': 'సమాచార కేంద్రం చదవండి',
    'home.helpBannerTitle': 'తక్షణ సహాయం కావాలా?',
    'home.helpBannerSub': 'రైతుల ప్రత్యక్ష మద్దతు & కాలుష్య అత్యవసర హెల్ప్‌లైన్',
    'home.helpBannerDesc': 'భూమి నమోదు, నేల పరీక్షలు లేదా కాలుష్య సమస్యల పరిష్కారం కోసం మా బృందాన్ని సంప్రదించండి.',

    // Awareness
    'aware.badge': 'ఈడెన్ సింక్ పర్యావరణ పరిజ్ఞానం & రైతు సాధికారత కేంద్రం',
    'aware.title': 'మట్టి, నీరు మరియు సహజ సాగు శాస్త్రం',
    'aware.subtitle': 'చిన్న మరియు సన్నకారు రైతుల కోసం 20 సహజ ఎరువుల తయారీ విధానాలు, చెరువుల పునరుద్ధరణ మరియు సేంద్రీయ కార్బన్ పెంపుదల గైడ్లు.',
    'aware.tabGuides': 'చిత్రాలతో గైడ్లు',
    'aware.tabRecipes': '20 సహజ ఎరువుల తయారీ విధానాలు',
    'aware.tabCalc': 'పర్యావరణ కాలిక్యులేటర్లు',
    'aware.tabMyths': 'అపోహలు vs వాస్తవాలు',
    'aware.tabBiofence': 'జీవ కంచె నమూనాలు',
    'aware.smallFarmerBadge': 'కొత్త & చిన్న రైతులకు ప్రత్యేకం (0.5 - 3 ఎకరాలు)',
    'aware.allCategories': 'అన్ని విభాగాలు',
    'aware.searchPlaceholder': 'జీవామృతం, సహజ ఎరువులు, కషాయాలు శోధించండి...',
    'aware.prepTime': 'తయారీ సమయం',
    'aware.shelfLife': 'నిల్వ కాలం',
    'aware.dilution': 'కలిపే నిష్పత్తి',
    'aware.costEst': 'అంచనా ఖర్చు',
    'aware.viewRecipeBtn': 'తయారీ విధానాన్ని చూడండి',
    'aware.ingredientsRequired': 'కావలసిన ముఖ్య పదార్థాలు',
    'aware.stepByStep': 'దశలవారీ తయారీ విధానం',
    'aware.keyBenefits': 'చిన్న రైతులకు ముఖ్య ప్రయోజనాలు',
    'aware.precautions': 'ముఖ్య జాగ్రత్తలు',

    // Soil Scanner
    'soil.scannerTitle': 'మట్టి మరియు నీటి AI ఫోటో డిటెక్టర్',
    'soil.scannerSub': 'మీ పొలం మట్టి లేదా నీటి ఫోటోను అప్‌లోడ్ చేసి క్షణాల్లో AI విశ్లేషణ మరియు పరిష్కారాలను పొందండి.',
    'soil.tabSoil': '🌱 నేల ఫోటో స్కానర్',
    'soil.tabWater': '💧 జలాశయం స్కానర్',
    'soil.uploadTitle': 'మట్టి ఫోటోను అప్‌లోడ్ చేయండి',
    'soil.uploadSub': 'JPG, PNG, WEBP సపోర్ట్ చేస్తుంది. పగటి వెలుతురులో ఫోటో తీయండి.',
    'soil.btnScan': 'AI తో విశ్లేషించండి',
    'soil.healthIndex': 'నేల ఆరోగ్య సూచిక',
    'soil.moistureLevel': 'తేమ శాతం',
    'soil.organicMatter': 'సేంద్రీయ పదార్థం',
    'soil.recommendations': 'తక్షణ కార్యాచరణ ప్రణాళిక',

    // Pollution
    'poll.title': 'భూమి & నీటి కాలుష్య నివారణ పోర్టల్',
    'poll.sub': 'కాలుష్య వ్యర్థాలు లేదా డ్రైనేజీ సమస్యలపై ఫిర్యాదు చేసి తక్షణ AI రక్షణ మార్గదర్శకాలను పొందండి.',
    'poll.btnFile': 'కొత్త కాలుష్య ఫిర్యాదు చేయండి',
    'poll.btnTrack': 'ఫిర్యాదు స్థితిని ట్రాక్ చేయండి',
    'poll.domainLand': 'భూమి & నేల కాలుష్యం',
    'poll.domainWater': 'నీరు & నదుల కాలుష్యం',

    // Footer
    'footer.brand': 'ఈడెన్ సింక్ పునరుద్ధరణ',
    'footer.sub': 'భూమి మరియు జలాశయాల పునరుజ్జీవన వేదిక',
    'footer.helplineLabel': 'హెల్ప్‌లైన్ & కాలుష్య నివేదిక నంబర్:',
    'footer.quote': '"భూమిని కాపాడుకుందాం, ప్రకృతితో కలిసి జీవిద్దాం."',
    'footer.copyright': '© 2026 ఈడెన్ సింక్ పునరుద్ధరణ నెట్‌వర్క్.',
  },
  kn: {
    // Nav
    'nav.brand': 'ಈಡನ್ ಸಿಂಕ್',
    'nav.revival': 'ಪುನರುಜ್ಜೀವನ',
    'nav.tagline': 'ಭೂಮಿ ಮತ್ತು ಜಲಮೂಲಗಳ ಪುನಶ್ಚೇತನ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.soilScanner': 'ಮಣ್ಣು AI ಸ್ಕ್ಯಾನರ್',
    'nav.pollution': 'ಮಾಲಿನ್ಯ ದೂರುಗಳು',
    'nav.customers': 'ಗ್ರಾಹಕರ ಡೇಟಾಬೇಸ್',
    'nav.elnino': 'ಎಲ್ ನಿನೋ & ಹವಾಮಾನ',
    'nav.govt': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'nav.register': 'ನೋಂದಣಿ',
    'nav.awareness': 'ಅರಿವು & ಮಾರ್ಗದರ್ಶಿಗಳು',
    'nav.portal': 'ಪೋರ್ಟಲ್',
    'nav.admin': 'ನಿರ್ವಾಹಕ',
    'nav.login': 'ಲಾಗಿನ್ / ಬದಲಾಯಿಸಿ',
    'nav.logout': 'ಲಾಗೌಟ್',
    'nav.call': 'ಕರೆ ಮಾಡಿ:',
    'nav.landowner': 'ಭೂಮಾಲೀಕ',
    'nav.adminUser': 'ನಿರ್ವಾಹಕ',

    // Hero
    'hero.badge': 'ಈಡನ್ ಸಿಂಕ್ ರಿವೈವಲ್ — ಭೂಮಿ ಮತ್ತು ಜಲಮೂಲಗಳ ಪುನಶ್ಚೇತನ',
    'hero.helpline': 'ತುರ್ತು ಸಹಾಯವಾಣಿ:',
    'hero.title1': 'ಈಡನ್ ಸಿಂಕ್ ರಿವೈವಲ್:',
    'hero.title2': 'ಭೂಮಿ ಮತ್ತು ಜಲಮೂಲಗಳ ಪುನಶ್ಚೇತನ',
    'hero.subtitle': 'ನಿಮ್ಮ ಕೃಷಿ ಭೂಮಿ, ಬಂಜರು ಮಣ್ಣು, ಕೆರೆ ಅಥವಾ ಕೊಳಗಳನ್ನು ಪುನರುಜ್ಜೀವನಗೊಳಿಸಲು ನೋಂದಾಯಿಸಿ ಅಥವಾ ಮಾಲಿನ್ಯದ ವಿರುದ್ಧ ದೂರು ನೀಡಿ. ನಾವು ರೈತರನ್ನು AI ಮಣ್ಣು ಪರೀಕ್ಷೆ, ಪರಿಸರ ತಜ್ಞರು ಮತ್ತು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    'hero.btnRegister': 'ಭೂಮಿ / ಜಲಮೂಲ ನೋಂದಾಯಿಸಿ',
    'hero.btnReportPollution': 'ಮಾಲಿನ್ಯ ವರದಿ ಮಾಡಿ',
    'hero.btnGovt': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'ಎಕರೆ ಭೂಮಿ ಪುನಶ್ಚೇತನ',
    'hero.stat1Sub': 'ಸಾವಯವ ಇಂಗಾಲ & pH ಸಮತೋಲನ',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'ಕೆರೆಗಳ ಹೂಳೆತ್ತುವಿಕೆ',
    'hero.stat2Sub': 'ಅಂತರ್ಜಲ ಮಟ್ಟ ಹೆಚ್ಚಳ',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'ಮಾಲಿನ್ಯ ದೂರುಗಳ ಪರಿಹಾರ',
    'hero.stat3Sub': 'ರಾಸಾಯನಿಕ ತ್ಯಾಜ್ಯ ಮುಕ್ತಿ',
    'hero.stat4Val': '₹48.2 ಕೋಟಿ',
    'hero.stat4Title': 'ಸರ್ಕಾರಿ ಅನುದಾನ ನೆರವು',
    'hero.stat4Sub': 'ರೈತರಿಗೆ ನೇರ ಸಬ್ಸಿಡಿ',

    // Home Features
    'home.pillarsTitle': 'ಪುನಶ್ಚೇತನ ಸ್ತಂಭಗಳು & ಪರಿಹಾರಗಳು',
    'home.pillarsHeader': 'ಈಡನ್ ಸಿಂಕ್ ರಿವೈವಲ್: ಪರಿಸರ ಸಂರಕ್ಷಣಾ ವ್ಯವಸ್ಥೆ',
    'home.pillarsSub': 'ಭೂ ನೋಂದಣಿ, ಮಾಲಿನ್ಯ ದೂರು ಪರಿಹಾರ, ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ ಮತ್ತು ಸರ್ಕಾರಿ ಅನುದಾನಗಳನ್ನು ಒಗ್ಗೂಡಿಸುವ ಡಿಜಿಟಲ್ ವೇದಿಕೆ.',
    'home.soilCardTitle': 'ಮಣ್ಣು AI ಫೋಟೋ ಸ್ಕ್ಯಾನರ್',
    'home.soilCardBadge': 'ಒಣ • ಜೇಡಿಮಣ್ಣು • ಫಲವತ್ತಾದ • ತೇವಾಂಶ ಮಣ್ಣು',
    'home.soilCardDesc': 'ನಿಮ್ಮ ಜಮೀನಿನ ಮಣ್ಣಿನ ಫೋಟೋ ತೆಗೆಯಿರಿ. AI ತಕ್ಷಣವೇ ಮಣ್ಣಿನ ವಿಧ, ತೇವಾಂಶ % ಗುರುತಿಸಿ ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ ತಯಾರಿಕೆಯ ಸಲಹೆ ನೀಡುತ್ತದೆ.',
    'home.soilCardBtn': 'ಮಣ್ಣಿನ ಫೋಟೋ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'home.pollCardTitle': 'ಭೂಮಿ ಮತ್ತು ಜಲ ಮಾಲಿನ್ಯ ದೂರುಗಳು',
    'home.pollCardBadge': 'AI ತ್ವರಿತ ಪರಿಹಾರ ಸಕ್ರಿಯ',
    'home.pollCardDesc': 'ರಾಸಾಯನಿಕ ತ್ಯಾಜ್ಯ, ಕೊಳಚೆ ನೀರು ಅಥವಾ ಪ್ಲಾಸ್ಟಿಕ್ ಎಸೆಯುವಿಕೆ ವಿರುದ್ಧ ದೂರು ದಾಖಲಿಸಿ ತಕ್ಷಣ AI ಪರಿಹಾರ ಪಡೆಯಿರಿ.',
    'home.pollCardBtn': 'ದೂರು ದಾಖಲಿಸಿ / ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'home.custCardTitle': 'ಗ್ರಾಹಕರ ಡೇಟಾಬೇಸ್',
    'home.custCardBadge': 'ನಿರ್ವಾಹಕರಿಗೆ ಮಾತ್ರ',
    'home.custCardDesc': 'ರೈತರ ಮಣ್ಣಿನ ಆರೋಗ್ಯ, pH, ಸಾವಯವ ಇಂಗಾಲ ಮತ್ತು ಪುನರುಜ್ಜೀವನ ಯೋಜನೆಗಳ ಮಾಹಿತಿ.',
    'home.custCardBtn': 'ಗ್ರಾಹಕರ ಪಟ್ಟಿ ವೀಕ್ಷಿಸಿ',
    'home.custCardBtnLogin': 'ವೀಕ್ಷಿಸಲು ಅಡ್ಮಿನ್ ಲಾಗಿನ್ ಮಾಡಿ',
    'home.elninoCardTitle': 'ಎಲ್ ನಿನೋ & ಹವಾಮಾನ ಬದಲಾವಣೆ',
    'home.elninoCardDesc': 'ತಾಪಮಾನ ಏರಿಳಿತಗಳು, ಮಳೆ ಕೊರತೆ ಅಂದಾಜು ಮತ್ತು ಬರ ಪರಿಸ್ಥಿತಿಯನ್ನು ಎದುರಿಸುವ ನೈಸರ್ಗಿಕ ಕೃಷಿ ಪದ್ಧತಿಗಳು.',
    'home.elninoCardBtn': 'ಹವಾಮಾನ ಕೇಂದ್ರ ವೀಕ್ಷಿಸಿ',
    'home.agriCardTitle': 'ಕೃಷಿ ಭೂಮಿ ಪುನರುಜ್ಜೀವನ',
    'home.agriCardDesc': 'ಸವಳು ಅಥವಾ ಬಂಜರು ಭೂಮಿಯನ್ನು ಹಸಿರೆಲೆ ಗೊಬ್ಬರ ಮತ್ತು ಸಾವಯವ ಹೊದಿಕೆಯ ಮೂಲಕ ಪುನಶ್ಚೇತನಗೊಳಿಸಿ.',
    'home.agriCardBtn': 'ನಿಮ್ಮ ಭೂಮಿ ನೋಂದಾಯಿಸಿ',
    'home.waterCardTitle': 'ಕೆರೆ ಮತ್ತು ಜಲಮೂಲಗಳ ಪುನಶ್ಚೇತನ',
    'home.waterCardDesc': 'ಕೆರೆಗಳ ಹೂಳೆತ್ತುವಿಕೆ, ಲಂಬ ಹುಲ್ಲಿನ (ವೆಟಿವರ್) ಬೆಳೆ ಮತ್ತು ಮಳೆನೀರು ಕೊಯ್ಲು ಕಾಮಗಾರಿಗಳು.',
    'home.waterCardBtn': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',
    'home.guideCardTitle': 'ವಿಜ್ಞಾನ & ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ ಮಾರ್ಗದರ್ಶಿ',
    'home.guideCardDesc': '20 ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ ತಯಾರಿಕಾ ವಿಧಾನಗಳು, ಹೂಳೆತ್ತುವ ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಪರಿಸರ ಸಂರಕ್ಷಣಾ ಕಾನೂನುಗಳು.',
    'home.guideCardBtn': 'ಜ್ಞಾನ ಕೇಂದ್ರ ಓದಿ',
    'home.helpBannerTitle': 'ತುರ್ತು ನೆರವು ಬೇಕೇ?',
    'home.helpBannerSub': 'ರೈತರ ನೇರ ಬೆಂಬಲ & ಮಾಲಿನ್ಯ ನಿಯಂತ್ರಣ ಸಹಾಯವಾಣಿ',
    'home.helpBannerDesc': 'ಭೂಮಿ ನೋಂದಣಿ, ಮಣ್ಣು ಪರೀಕ್ಷೆ ವರದಿಗಳು ಅಥವಾ ಮಾಲಿನ್ಯ ಸಮಸ್ಯೆಗಳ ಪರಿಹಾರಕ್ಕಾಗಿ ನಮ್ಮ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ.',

    // Awareness
    'aware.badge': 'ಈಡನ್ ಸಿಂಕ್ ಪರಿಸರ ಜ್ಞಾನ ಮತ್ತು ರೈತರ ಸಬಲೀಕರಣ ಕೇಂದ್ರ',
    'aware.title': 'ಮಣ್ಣು, ನೀರು ಮತ್ತು ನೈಸರ್ಗಿಕ ಕೃಷಿ ವಿಜ್ಞಾನ',
    'aware.subtitle': 'ಸಣ್ಣ ಮತ್ತು ಹೊಸ ರೈತರಿಗಾಗಿ 20 ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ ತಯಾರಿಕಾ ವಿಧಾನಗಳು, ಕೆರೆ ಹೂಳೆತ್ತುವಿಕೆ ಮತ್ತು ಸಾವಯವ ಇಂಗಾಲ ಹೆಚ್ಚಿಸುವ ಮಾರ್ಗದರ್ಶಿಗಳು.',
    'aware.tabGuides': 'ಚಿತ್ರ ಸಹಿತ ಮಾರ್ಗದರ್ಶಿಗಳು',
    'aware.tabRecipes': '20 ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ ತಯಾರಿಕಾ ವಿಧಾನಗಳು',
    'aware.tabCalc': 'ಪರಿಸರ ಕ್ಯಾಲ್ಕುಲೇಟರ್‌ಗಳು',
    'aware.tabMyths': 'ತಪ್ಪು ಕಲ್ಪನೆಗಳು vs ವಾಸ್ತವ ಸತ್ಯ',
    'aware.tabBiofence': 'ಜೈವಿಕ ಬೇಲಿ ಯೋಜನೆಗಳು',
    'aware.smallFarmerBadge': 'ಸಣ್ಣ ಮತ್ತು ಅತಿ ಸಣ್ಣ ರೈತರಿಗಾಗಿ (0.5 - 3 ಎಕರೆ)',
    'aware.allCategories': 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    'aware.searchPlaceholder': 'ಜೀವಾಮೃತ, ನೈಸರ್ಗಿಕ ಗೊಬ್ಬರ, ಕಷಾಯ ಹುಡುಕಿ...',
    'aware.prepTime': 'ತಯಾರಿಕಾ ಸಮಯ',
    'aware.shelfLife': 'ಬಳಕೆಯ ಅವಧಿ',
    'aware.dilution': 'ಮಿಶ್ರಣದ ಪ್ರಮಾಣ',
    'aware.costEst': 'ಅಂದಾಜು ವೆಚ್ಚ',
    'aware.viewRecipeBtn': 'ಹಂತ ಹಂತದ ತಯಾರಿಕಾ ವಿಧಾನ ನೋಡಿ',
    'aware.ingredientsRequired': 'ಅಗತ್ಯವಿರುವ ಮುಖ್ಯ ಸಾಮಗ್ರಿಗಳು',
    'aware.stepByStep': 'ಹಂತ ಹಂತದ ತಯಾರಿಕಾ ವಿಧಾನ',
    'aware.keyBenefits': 'ಸಣ್ಣ ರೈತರಿಗೆ ಮುಖ್ಯ ಪ್ರಯೋಜನಗಳು',
    'aware.precautions': 'ಮುಖ್ಯ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು',

    // Soil Scanner
    'soil.scannerTitle': 'ಮಣ್ಣು ಮತ್ತು ನೀರು AI ಫೋಟೋ ಡಿಟೆಕ್ಟರ್',
    'soil.scannerSub': 'ನಿಮ್ಮ ಜಮೀನಿನ ಮಣ್ಣು ಅಥವಾ ಜಲಮೂಲದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ತಕ್ಷಣವೇ AI ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಪರಿಹಾರಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'soil.tabSoil': '🌱 ಮಣ್ಣಿನ ಫೋಟೋ ಸ್ಕ್ಯಾನರ್',
    'soil.tabWater': '💧 ಜಲಮೂಲ ಸ್ಕ್ಯಾನರ್',
    'soil.uploadTitle': 'ಮಣ್ಣಿನ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'soil.uploadSub': 'JPG, PNG, WEBP ಬೆಂಬಲಿಸುತ್ತದೆ. ನೈಸರ್ಗಿಕ ಬೆಳಕಿನಲ್ಲಿ ಫೋಟೋ ತೆಗೆಯಿರಿ.',
    'soil.btnScan': 'AI ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಿ',
    'soil.healthIndex': 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ',
    'soil.moistureLevel': 'ತೇವಾಂಶದ ಮಟ್ಟ',
    'soil.organicMatter': 'ಸಾವಯವ ವಸ್ತು',
    'soil.recommendations': 'ತಕ್ಷಣದ ಕಾರ್ಯ ಯೋಜನೆ',

    // Pollution
    'poll.title': 'ಭೂಮಿ & ಜಲ ಮಾಲಿನ್ಯ ನಿವಾರಣಾ ಪೋರ್ಟಲ್',
    'poll.sub': 'ರಾಸಾಯನಿಕ ತ್ಯಾಜ್ಯ ಅಥವಾ ಒಳಚರಂಡಿ ಮಾಲಿನ್ಯದ ವಿರುದ್ಧ ದೂರು ದಾಖಲಿಸಿ ತಕ್ಷಣ AI ರಕ್ಷಣಾ ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'poll.btnFile': 'ಹೊಸ ಮಾಲಿನ್ಯ ದೂರು ದಾಖಲಿಸಿ',
    'poll.btnTrack': 'ದೂರಿನ ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'poll.domainLand': 'ಭೂಮಿ ಮತ್ತು ಮಣ್ಣಿನ ಮಾಲಿನ್ಯ',
    'poll.domainWater': 'ನೀರು ಮತ್ತು ನದಿಗಳ ಮಾಲಿನ್ಯ',

    // Footer
    'footer.brand': 'ಈಡನ್ ಸಿಂಕ್ ರಿವೈವಲ್',
    'footer.sub': 'ಭೂಮಿ ಮತ್ತು ಜಲಮೂಲಗಳ ಪುನಶ್ಚೇತನ ವೇದಿಕೆ',
    'footer.helplineLabel': 'ಸಹಾಯವಾಣಿ & ಮಾಲಿನ್ಯ ವರದಿ ಸಂಖ್ಯೆ:',
    'footer.quote': '"ಭೂಮಿಯನ್ನು ರಕ್ಷಿಸೋಣ, ಪ್ರಕೃತಿಯೊಂದಿಗೆ ಬದುಕೋಣ."',
    'footer.copyright': '© 2026 ಈಡನ್ ಸಿಂಕ್ ರಿವೈವಲ್ ನೆಟ್‌ವರ್ಕ್.',
  },
  ml: {
    // Nav
    'nav.brand': 'ഈഡൻ സിങ്ക്',
    'nav.revival': 'പുനരുജ്ജീവനം',
    'nav.tagline': 'മണ്ണും ജലാശയങ്ങളും വീണ്ടെടുക്കൽ',
    'nav.home': 'ഹോം',
    'nav.soilScanner': 'മണ്ണ് AI സ്കാനർ',
    'nav.pollution': 'മലിനീകരണ പരാതികൾ',
    'nav.customers': 'ഉപഭോക്തൃ ഡാറ്റാബേസ്',
    'nav.elnino': 'എൽ നിനോ & കാലാവസ്ഥ',
    'nav.govt': 'സർക്കാർ പദ്ധതികൾ',
    'nav.register': 'രജിസ്ട്രേഷൻ',
    'nav.awareness': 'അവബോധവും വഴികാട്ടികളും',
    'nav.portal': 'പോർട്ടൽ',
    'nav.admin': 'അഡ്മിൻ',
    'nav.login': 'ലോഗിൻ / മാറ്റുക',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    'nav.call': 'വിളിക്കുക:',
    'nav.landowner': 'ഭൂവുടമ',
    'nav.adminUser': 'അഡ്മിൻ',

    // Hero
    'hero.badge': 'ഈഡൻ സിങ്ക് — മണ്ണും ജലാശയങ്ങളും സംരക്ഷിക്കാനുള്ള കൂട്ടായ്മ',
    'hero.helpline': 'ഹെൽപ്പ്‌ലൈൻ:',
    'hero.title1': 'ഈഡൻ സിങ്ക് റിവൈവൽ:',
    'hero.title2': 'ഭൂമിയും ജലാശയങ്ങളും പുനരുജ്ജീവിപ്പിക്കൽ',
    'hero.subtitle': 'കൃഷിഭൂമി, തരിശുനിലം, കുളങ്ങൾ, ജലാശയങ്ങൾ എന്നിവ വീണ്ടെടുക്കാൻ രജിസ്റ്റർ ചെയ്യുക. മാലിന്യം തള്ളുന്നതിനെതിരെ പരാതി നൽകുക.',
    'hero.btnRegister': 'ഭൂമി / ജലാശയം രജിസ്റ്റർ ചെയ്യുക',
    'hero.btnReportPollution': 'മലിനീകരണം റിപ്പോർട്ട് ചെയ്യുക',
    'hero.btnGovt': 'സർക്കാർ പദ്ധതികൾ',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'ഏക്കർ ഭൂമി വീണ്ടെടുത്തു',
    'hero.stat1Sub': 'ജൈവ കാർബൺ വർദ്ധനവ്',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'കുളങ്ങൾ വൃത്തിയാക്കി',
    'hero.stat2Sub': 'ഭൂഗർഭജല റീചാർജ്ജ്',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'പരാതികൾ പരിഹരിച്ചു',
    'hero.stat3Sub': 'മാലിന്യ നിർമ്മാർജ്ജനം',
    'hero.stat4Val': '₹48.2 കോടി',
    'hero.stat4Title': 'സർക്കാർ സബ്‌സിഡികൾ',
    'hero.stat4Sub': 'കർഷകർക്കുള്ള ധനസഹായം',

    // Home Features
    'home.pillarsTitle': 'പുനരുജ്ജീവന സ്തംഭങ്ങൾ',
    'home.pillarsHeader': 'ഈഡൻ സിങ്ക്: ഭൂമി & ജല സംരക്ഷണ ശൃംഖല',
    'home.pillarsSub': 'ഭൂവുടമകളുടെ രജിസ്ട്രേഷൻ, മലിനീകരണ പരാതികൾ, കാലാവസ്ഥാ വിവരങ്ങൾ എന്നിവ സംയോജിപ്പിക്കുന്ന പ്ലാറ്റ്‌ഫോം.',
    'home.soilCardTitle': 'മണ്ണ് AI ഫോട്ടോ സ്കാനർ',
    'home.soilCardBadge': 'വരണ്ട • കളിമണ്ണ് • ഫലഭൂയിഷ്ഠം',
    'home.soilCardDesc': 'മണ്ണിന്റെ ഫോട്ടോ എടുത്ത് അപ്‌ലോഡ് ചെയ്യുക. AI തൽക്ഷണം മണ്ണിന്റെ ഗുണം പരിശോധിച്ച് ജൈവ വളങ്ങൾ ശുപാർശ ചെയ്യുന്നു.',
    'home.soilCardBtn': 'മണ്ണ് സ്കാൻ ചെയ്യുക',
    'home.pollCardTitle': 'മലിനീകരണ പരാതികൾ',
    'home.pollCardBadge': 'AI വേഗത്തിലുള്ള പരിഹാരം',
    'home.pollCardDesc': 'രാസമാലിന്യങ്ങൾ, പ്ലാസ്റ്റിക് അല്ലെങ്കിൽ മലിനജലം തള്ളുന്നതിനെതിരെ പരാതിപ്പെടുക.',
    'home.pollCardBtn': 'പരാതി സമർപ്പിക്കുക',
    'home.custCardTitle': 'ഉപഭോക്തൃ ഡാറ്റാബേസ്',
    'home.custCardBadge': 'അഡ്മിന് മാത്രം',
    'home.custCardDesc': 'കർഷകരുടെ മണ്ണ് പരിശോധന റിപ്പോർട്ടുകളും കാർഷിക വിവരങ്ങളും.',
    'home.custCardBtn': 'ഡാറ്റാബേസ് കാണുക',
    'home.custCardBtnLogin': 'ലോഗിൻ ചെയ്യുക',
    'home.elninoCardTitle': 'എൽ നിനോ & കാലാവസ്ഥ',
    'home.elninoCardDesc': 'താപനില മാറ്റങ്ങൾ, മഴ വിവരങ്ങൾ, പ്രകൃതിദത്ത കൃഷി രീതികൾ.',
    'home.elninoCardBtn': 'വിവരങ്ങൾ അറിയുക',
    'home.agriCardTitle': 'കൃഷിഭൂമി സംരക്ഷണം',
    'home.agriCardDesc': 'തരിശുഭൂമികൾ ജൈവവളങ്ങൾ ഉപയോഗിച്ച് ഫലഭൂയിഷ്ഠമാക്കുക.',
    'home.agriCardBtn': 'രജിസ്റ്റർ ചെയ്യുക',
    'home.waterCardTitle': 'ജലാശയ പുനരുദ്ധാരണം',
    'home.waterCardDesc': 'കുളങ്ങൾ വൃത്തിയാക്കൽ, രാമച്ചം വച്ചുപിടിപ്പിക്കൽ, മഴവെള്ള സംഭരണം.',
    'home.waterCardBtn': 'പദ്ധതികൾ കാണുക',
    'home.guideCardTitle': 'ജൈവവള നിർമ്മാണ വഴികാട്ടി',
    'home.guideCardDesc': '20 പ്രകൃതിദത്ത വളങ്ങൾ നിർമ്മിക്കുന്ന രീതികൾ, ജൈവ കീടനാശിനികൾ.',
    'home.guideCardBtn': 'വായിക്കുക',
    'home.helpBannerTitle': 'സഹായം ആവശ്യമുണ്ടോ?',
    'home.helpBannerSub': 'കർഷക സഹായ ഹെൽപ്പ്‌ലൈൻ',
    'home.helpBannerDesc': 'ഭൂമി രജിസ്ട്രേഷൻ, മണ്ണ് പരിശോധന എന്നിവയിൽ വിദഗ്ദ്ധ സഹായം ലഭ്യമാണ്.',

    // Awareness
    'aware.badge': 'ഈഡൻ സിങ്ക് പരിസ്ഥിതി & കർഷക ശാക്തീകരണ കേന്ദ്രം',
    'aware.title': 'മണ്ണ്, ജലം, പ്രകൃതി കൃഷി ശാസ്ത്രം',
    'aware.subtitle': 'ചെറുകിട കർഷകർക്കായി 20 ജൈവ വളങ്ങൾ നിർമ്മിക്കുന്ന രീതികൾ, കുളം നവീകരണം, ജൈവ കാർബൺ വർദ്ധിപ്പിക്കൽ.',
    'aware.tabGuides': 'ഗൈഡുകൾ',
    'aware.tabRecipes': '20 ജൈവ വള നിർമ്മാണ രീതികൾ',
    'aware.tabCalc': 'ഇക്കോ കാൽക്കുലേറ്ററുകൾ',
    'aware.tabMyths': 'ധാരണകളും യാഥാർത്ഥ്യങ്ങളും',
    'aware.tabBiofence': 'ജൈവ വേലി മാതൃകകൾ',
    'aware.smallFarmerBadge': 'ചെറുകിട കർഷകർക്കായി (0.5 - 3 ഏക്കർ)',
    'aware.allCategories': 'എല്ലാ വിഭാഗങ്ങളും',
    'aware.searchPlaceholder': 'ജീവാമൃതം, ജൈവവളങ്ങൾ, കഷായങ്ങൾ തിരയുക...',
    'aware.prepTime': 'തയ്യാറാക്കാൻ വേണ്ട സമയം',
    'aware.shelfLife': 'ഉപയോഗ കാലാവധി',
    'aware.dilution': 'നേർപ്പിക്കുന്ന അനുപാതം',
    'aware.costEst': 'ഏകദേശ ചെലവ്',
    'aware.viewRecipeBtn': 'നിർമ്മാണ രീതി കാണുക',
    'aware.ingredientsRequired': 'ആവശ്യമായ സാധനങ്ങൾ',
    'aware.stepByStep': 'തയ്യാറാക്കുന്ന വിധം',
    'aware.keyBenefits': 'പ്രധാന ഗുണങ്ങൾ',
    'aware.precautions': 'ശ്രദ്ധിക്കേണ്ട കാര്യങ്ങൾ',

    // Soil Scanner
    'soil.scannerTitle': 'മണ്ണ് & ജല AI ഫോട്ടോ ഡിറ്റക്ടർ',
    'soil.scannerSub': 'മണ്ണിന്റെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്ത് ഗുണനിലവാരം പരിശോധിക്കുക.',
    'soil.tabSoil': '🌱 മണ്ണ് സ്കാനർ',
    'soil.tabWater': '💧 ജലാശയ സ്കാനർ',
    'soil.uploadTitle': 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    'soil.uploadSub': 'സ്വാഭാവിക വെളിച്ചത്തിൽ എടുത്ത ഫോട്ടോ നൽകുക.',
    'soil.btnScan': 'AI പരിശോധന നടത്തുക',
    'soil.healthIndex': 'മണ്ണിന്റെ ആരോഗ്യ സൂചിക',
    'soil.moistureLevel': 'ഈർപ്പത്തിന്റെ അളവ്',
    'soil.organicMatter': 'ജൈവാംശം',
    'soil.recommendations': 'ഉടൻ ചെയ്യേണ്ട കാര്യങ്ങൾ',

    // Pollution
    'poll.title': 'മലിനീകരണ പരാതി പരിഹാര പോർട്ടൽ',
    'poll.sub': 'മലിനീകരണ സംഭവങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക.',
    'poll.btnFile': 'പരാതി നൽകുക',
    'poll.btnTrack': 'പരാതിയുടെ അവസ്ഥ പരിശോധിക്കുക',
    'poll.domainLand': 'മണ്ണ് മലിനീകരണം',
    'poll.domainWater': 'ജല മലിനീകരണം',

    // Footer
    'footer.brand': 'ഈഡൻ സിങ്ക് റിവൈവൽ',
    'footer.sub': 'മണ്ണും ജലാശയങ്ങളും പുനരുജ്ജീവിപ്പിക്കാനുള്ള കൂട്ടായ്മ',
    'footer.helplineLabel': 'ഹെൽപ്പ്‌ലൈൻ നമ്പർ:',
    'footer.quote': '"ഭൂമിയെ വീണ്ടെടുക്കാം, പ്രകൃതിയോട് ചേർന്ന് ജീവിക്കാം."',
    'footer.copyright': '© 2026 ഈഡൻ സിങ്ക് റിവൈവൽ നെറ്റ്വർക്ക്.',
  },
  bn: {
    // Nav
    'nav.brand': 'ইডেন সিঙ্ক',
    'nav.revival': 'পুনরুজ্জীবন',
    'nav.tagline': 'ভূমি ও জলাশয় পুনরুদ্ধার',
    'nav.home': 'হোম',
    'nav.soilScanner': 'মাটি AI স্ক্যানার',
    'nav.pollution': 'দূষণ অভিযোগ',
    'nav.customers': 'গ্রাহক তথ্যভাণ্ডার',
    'nav.elnino': 'এল নিনো ও জলবায়ু',
    'nav.govt': 'সরকারি প্রকল্প',
    'nav.register': 'নিবন্ধন',
    'nav.awareness': 'সচেতনতা ও নির্দেশিকা',
    'nav.portal': 'পোর্টাল',
    'nav.admin': 'অ্যাডমিন',
    'nav.login': 'লগইন / পরিবর্তন',
    'nav.logout': 'লগ আউট',
    'nav.call': 'কল করুন:',
    'nav.landowner': 'জমি মালিক',
    'nav.adminUser': 'অ্যাডমিন',

    // Hero
    'hero.badge': 'ইডেন সিঙ্ক রিভাইভাল — ভূমি ও জলাশয় পুনরুজ্জীবন পরিবেশ',
    'hero.helpline': 'জরুরি হেল্পলাইন:',
    'hero.title1': 'ইডেন সিঙ্ক রিভাইভাল:',
    'hero.title2': 'ভূমি ও জলাশয় পুনরুজ্জীবন',
    'hero.subtitle': 'আপনার কৃষি জমি, পতিত জমি, পুকুর বা জলাশয় পুনরুদ্ধারের জন্য নিবন্ধন করুন অথবা অবৈধ দূষণের বিরুদ্ধে অভিযোগ জানান।',
    'hero.btnRegister': 'জমি / জলাশয় নিবন্ধন করুন',
    'hero.btnReportPollution': 'দূষণের অভিযোগ জানান',
    'hero.btnGovt': 'সরকারি প্রকল্পসমূহ',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'একর জমি পুনরুদ্ধার',
    'hero.stat1Sub': 'জৈব কার্বন বৃদ্ধি',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'জলাশয় খনন ও সংস্কার',
    'hero.stat2Sub': 'ভূগর্ভস্থ জল রিচার্জ',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'দূষণ সমস্যার সমাধান',
    'hero.stat3Sub': 'রাসায়নিক বর্জ্য মুক্ত',
    'hero.stat4Val': '₹48.2 কোটি',
    'hero.stat4Title': 'সরকারি অনুদান',
    'hero.stat4Sub': 'কৃষকদের সহায়তা',

    // Home Features
    'home.pillarsTitle': 'পুনরুদ্ধার ও সমাধান',
    'home.pillarsHeader': 'ইডেন সিঙ্ক: জমি ও জল সংরক্ষণের ডিজিটাল মঞ্চ',
    'home.pillarsSub': 'কৃষক নিবন্ধন, দূষণ অভিযোগ, আবহাওয়া তথ্য ও সরকারি অনুদানের সমন্বয়।',
    'home.soilCardTitle': 'মাটি AI ফটো স্ক্যানার',
    'home.soilCardBadge': 'শুষ্ক • এটেল • উর্বর • আর্দ্র',
    'home.soilCardDesc': 'আপনার জমির মাটির ছবি তুলুন। AI তাৎক্ষণিকভাবে মাটির গুণাগুণ পরীক্ষা করে জৈব সার তৈরির পরামর্শ দেবে।',
    'home.soilCardBtn': 'মাটির ছবি স্ক্যান করুন',
    'home.pollCardTitle': 'ভূমি ও জল দূষণ অভিযোগ',
    'home.pollCardBadge': 'AI দ্রুত সমাধান সক্রিয়',
    'home.pollCardDesc': 'রাসায়নিক বর্জ্য, প্লাস্টিক বা নর্দমার জলের বিরুদ্ধে অভিযোগ জানান।',
    'home.pollCardBtn': 'অভিযোগ করুন / ট্র্যাক করুন',
    'home.custCardTitle': 'গ্রাহক তথ্যভাণ্ডার',
    'home.custCardBadge': 'শুধুমাত্র অ্যাডমিন',
    'home.custCardDesc': 'কৃষকদের জমির স্বাস্থ্য ও পুনরুদ্ধার সংক্রান্ত তথ্য।',
    'home.custCardBtn': 'তথ্যভাণ্ডার দেখুন',
    'home.custCardBtnLogin': 'অ্যাডমিন লগইন',
    'home.elninoCardTitle': 'এল নিনো ও জলবায়ু',
    'home.elninoCardDesc': 'তাপমাত্রার পরিবর্তন, খরার পূর্বাভাস ও প্রাকৃতিক কৃষি পদ্ধতি।',
    'home.elninoCardBtn': 'জলবায়ু কেন্দ্র দেখুন',
    'home.agriCardTitle': 'কৃষি জমি পুনরুজ্জীবন',
    'home.agriCardDesc': 'পতিত জমিকে সবুজ সার ও জৈব উপায়ে উর্বর করে তুলুন।',
    'home.agriCardBtn': 'জমি নিবন্ধন করুন',
    'home.waterCardTitle': 'জলাশয় সংস্কার',
    'home.waterCardDesc': 'পুকুর সংস্কার, ভেটিভার ঘাস রোপণ ও বৃষ্টির জল সংরক্ষণ।',
    'home.waterCardBtn': 'প্রকল্প দেখুন',
    'home.guideCardTitle': 'প্রাকৃতিক সার ও বিজ্ঞান',
    'home.guideCardDesc': '২০টি প্রাকৃতিক সার তৈরির পদ্ধতি, কীটনাশক ও আইনকানুন।',
    'home.guideCardBtn': 'জ্ঞান কেন্দ্র পড়ুন',
    'home.helpBannerTitle': 'সাহায্য প্রয়োজন?',
    'home.helpBannerSub': 'কৃষক সহায়তা হেল্পলাইন',
    'home.helpBannerDesc': 'জমি নিবন্ধন, মাটি পরীক্ষা ও দূষণ সংক্রান্ত সহায়তায় আমাদের টিম সর্বদা প্রস্তুত।',

    // Awareness
    'aware.badge': 'ইডেন সিঙ্ক পরিবেশ জ্ঞান ও কৃষক ক্ষমতায়ন কেন্দ্র',
    'aware.title': 'মাটি, জল ও প্রাকৃতিক কৃষির বিজ্ঞান',
    'aware.subtitle': 'ক্ষুদ্র ও নতুন কৃষকদের জন্য ২০টি প্রাকৃতিক সার তৈরির প্রস্তুতপ্রণালী, পুকুর সংস্কার ও মাটির উর্বরতা বৃদ্ধি।',
    'aware.tabGuides': 'সচিত্র নির্দেশিকা',
    'aware.tabRecipes': '২০টি প্রাকৃতিক সার প্রস্তুতপ্রণালী',
    'aware.tabCalc': 'ইকো ক্যালকুলেটর',
    'aware.tabMyths': 'ভুল ধারণা বনাম বিজ্ঞান',
    'aware.tabBiofence': 'জৈব বেড়া পরিকল্পনা',
    'aware.smallFarmerBadge': 'ক্ষুদ্র কৃষকদের জন্য বিশেষ উপযোগী (০.৫ - ৩ একর)',
    'aware.allCategories': 'সকল বিভাগ',
    'aware.searchPlaceholder': 'জীবামৃত, প্রাকৃতিক সার, ক্বাথ অনুসন্ধান করুন...',
    'aware.prepTime': 'প্রস্তুতির সময়',
    'aware.shelfLife': 'মেয়াদ',
    'aware.dilution': 'মিশ্রণের অনুপাত',
    'aware.costEst': 'আনুমানিক খরচ',
    'aware.viewRecipeBtn': 'প্রস্তুতপ্রণালী দেখুন',
    'aware.ingredientsRequired': 'প্রয়োজনীয় উপকরণ',
    'aware.stepByStep': 'ধাপে ধাপে প্রস্তুতপ্রণালী',
    'aware.keyBenefits': 'প্রধান সুবিধাসমূহ',
    'aware.precautions': 'জরুরি সতর্কতা',

    // Soil Scanner
    'soil.scannerTitle': 'মাটি ও জল AI ফটো ডিটেক্টর',
    'soil.scannerSub': 'মাটি বা জলের ছবি আপলোড করে দ্রুত AI বিশ্লেষণ ও সমাধান পান।',
    'soil.tabSoil': '🌱 মাটি স্ক্যানার',
    'soil.tabWater': '💧 জলাশয় স্ক্যানার',
    'soil.uploadTitle': 'ছবির নমুনা আপলোড করুন',
    'soil.uploadSub': 'দিনের আলোয় তোলা ছবি ব্যবহার করুন।',
    'soil.btnScan': 'AI বিশ্লেষণ করুন',
    'soil.healthIndex': 'মাটির স্বাস্থ্য সূচক',
    'soil.moistureLevel': 'আর্দ্রতার মাত্রা',
    'soil.organicMatter': 'জৈব উপাদান',
    'soil.recommendations': 'করণীয় পদক্ষেপ',

    // Pollution
    'poll.title': 'দূষণ অভিযোগ প্রতিকার পোর্টাল',
    'poll.sub': 'দূষণের ঘটনা জানান এবং তাৎক্ষণিক AI প্রতিকার পান।',
    'poll.btnFile': 'নতুন অভিযোগ করুন',
    'poll.btnTrack': 'অভিযোগের স্থিতি দেখুন',
    'poll.domainLand': 'ভূমি দূষণ',
    'poll.domainWater': 'জল দূষণ',

    // Footer
    'footer.brand': 'ইডেন সিঙ্ক রিভাইভাল',
    'footer.sub': 'ভূমি ও জলাশয় পুনরুজ্জীবন নেটওয়ার্ক',
    'footer.helplineLabel': 'হেল্পলাইন নম্বর:',
    'footer.quote': '"পৃথিবীকে বাঁচাই, প্রকৃতির সাথে বাঁচি।"',
    'footer.copyright': '© ২০২৬ ইডেন সিঙ্ক রিভাইভাল।',
  },
  mr: {
    // Nav
    'nav.brand': 'इडन सिंक',
    'nav.revival': 'पुनरुज्जीवन',
    'nav.tagline': 'जमीन व जलस्रोत पुनरुज्जीवन',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.soilScanner': 'माती AI स्कॅनर',
    'nav.pollution': 'प्रदूषण तक्रारी',
    'nav.customers': 'ग्राहक डेटाबेस',
    'nav.elnino': 'अल निनो व हवामान',
    'nav.govt': 'शासकीय प्रकल्प',
    'nav.register': 'नोंदणी',
    'nav.awareness': 'माहिती व मार्गदर्शिका',
    'nav.portal': 'पोर्टल',
    'nav.admin': 'अॅडमिन',
    'nav.login': 'लॉगिन / बदला',
    'nav.logout': 'लॉगआउट',
    'nav.call': 'कॉल करा:',
    'nav.landowner': 'जमीन मालक',
    'nav.adminUser': 'अॅडमिन',

    // Hero
    'hero.badge': 'इडन सिंक रिव्हायव्हल — जमीन व जलस्रोत पुनरुज्जीवन परिसंस्था',
    'hero.helpline': 'आपत्कालीन हेल्पलाइन:',
    'hero.title1': 'इडन सिंक रिव्हायव्हल:',
    'hero.title2': 'जमीन व जलस्रोत पुनरुज्जीवन',
    'hero.subtitle': 'आपली शेतजमीन, नापीक जमीन, तलाव किंवा पाण्याचे स्रोत पुनरुज्जीवित करण्यासाठी नोंदणी करा किंवा रासायनिक प्रदूषणाविरुद्ध तक्रार नोंदवा.',
    'hero.btnRegister': 'जमीन / जलस्रोत नोंदवा',
    'hero.btnReportPollution': 'प्रदूषणाची तक्रार करा',
    'hero.btnGovt': 'शासकीय योजना',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'एकर जमीन पुनरुज्जीवित',
    'hero.stat1Sub': 'सेंद्रिय कर्ब व pH समतोल',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'तलाव गाळमुक्त',
    'hero.stat2Sub': 'भूजल पातळीत वाढ',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'प्रदूषण तक्रारींचे निवारण',
    'hero.stat3Sub': 'रासायनिक कचरा मुक्ती',
    'hero.stat4Val': '₹48.2 कोटी',
    'hero.stat4Title': 'शासकीय अनुदान',
    'hero.stat4Sub': 'शेतकऱ्यांना थेट मदत',

    // Home Features
    'home.pillarsTitle': 'पुनरुज्जीवन व उपाय',
    'home.pillarsHeader': 'इडन सिंक: जमीन व पाणी संरक्षणाचे डिजिटल व्यासपीठ',
    'home.pillarsSub': 'शेतकरी नोंदणी, प्रदूषण तक्रार निवारण, हवामान अंदाज व शासकीय अनुदानांचे एकत्रिकरण.',
    'home.soilCardTitle': 'माती AI फोटो स्कॅनर',
    'home.soilCardBadge': 'कोरडी • चिकणमाती • सुपीक • ओलसर',
    'home.soilCardDesc': 'आपल्या शेतातील मातीचा फोटो काढा. AI त्वरित मातीचा प्रकार ओळखून नैसर्गिक खतांचे मार्गदर्शन देईल.',
    'home.soilCardBtn': 'मातीचा फोटो स्कॅन करा',
    'home.pollCardTitle': 'जमीन व जल प्रदूषण तक्रारी',
    'home.pollCardBadge': 'AI त्वरित उपाय सक्रिय',
    'home.pollCardDesc': 'रासायनिक कचरा, सांडपाणी किंवा प्लास्टिक कचरा टाकण्याविरुद्ध तक्रार करा.',
    'home.pollCardBtn': 'तक्रार नोंदवा / तपासा',
    'home.custCardTitle': 'ग्राहक डेटाबेस',
    'home.custCardBadge': 'केवळ अॅडमिनसाठी',
    'home.custCardDesc': 'शेतकऱ्यांची माती आरोग्य माहिती व पुनरुज्जीवन आराखडे.',
    'home.custCardBtn': 'डेटाबेस पहा',
    'home.custCardBtnLogin': 'अॅडमिन लॉगिन',
    'home.elninoCardTitle': 'अल निनो व हवामान',
    'home.elninoCardDesc': 'तापमानातील बदल, पावसाचा अंदाज व दुष्काळ निवारण पद्धती.',
    'home.elninoCardBtn': 'हवामान केंद्र पहा',
    'home.agriCardTitle': 'शेतजमीन पुनरुज्जीवन',
    'home.agriCardDesc': 'नापीक जमिनीवर सेंद्रिय खत व हिरवळीच्या खतांचा वापर करा.',
    'home.agriCardBtn': 'जमीन नोंदणी करा',
    'home.waterCardTitle': 'जलस्रोत पुनरुज्जीवन',
    'home.waterCardDesc': 'तलावातील गाळ काढणे, वाळा गवत लागवड व जलसंधारण.',
    'home.waterCardBtn': 'प्रकल्प पहा',
    'home.guideCardTitle': 'विज्ञान व सेंद्रिय खते',
    'home.guideCardDesc': '२० नैसर्गिक खते बनवण्याच्या पद्धती, गाळ काढणे व कायदे.',
    'home.guideCardBtn': 'माहिती केंद्र वाचा',
    'home.helpBannerTitle': 'मदत हवी आहे का?',
    'home.helpBannerSub': 'शेतकरी थेट मदत हेल्पलाइन',
    'home.helpBannerDesc': 'जमीन नोंदणी, माती परीक्षण व प्रदूषण तक्रारींसाठी आमची टीम तत्पर आहे.',

    // Awareness
    'aware.badge': 'इडन सिंक पर्यावरण ज्ञान व शेतकरी सक्षमीकरण केंद्र',
    'aware.title': 'माती, पाणी व नैसर्गिक शेतीचे विज्ञान',
    'aware.subtitle': 'लहान व नवीन शेतकऱ्यांसाठी २० नैसर्गिक खते बनवण्याच्या पद्धती, तलाव संवर्धन व सेंद्रिय कर्ब वाढवणे.',
    'aware.tabGuides': 'मार्गदर्शिका',
    'aware.tabRecipes': '२० नैसर्गिक खत निर्मिती पद्धती',
    'aware.tabCalc': 'पर्यावरण कॅल्क्युलेटर',
    'aware.tabMyths': 'गैरसमज विरुद्ध विज्ञान',
    'aware.tabBiofence': 'जैविक कुंपण योजना',
    'aware.smallFarmerBadge': 'लहान शेतकऱ्यांसाठी उपयुक्त (०.५ ते ३ एकर)',
    'aware.allCategories': 'सर्व श्रेणी',
    'aware.searchPlaceholder': 'जीवामृत, सेंद्रिय खत, कीटकनाशक शोधा...',
    'aware.prepTime': 'बनवण्याचा वेळ',
    'aware.shelfLife': 'वापरण्याचा कालावधी',
    'aware.dilution': 'मिश्रणाचे प्रमाण',
    'aware.costEst': 'अंदाजे खर्च',
    'aware.viewRecipeBtn': 'कृती पहा',
    'aware.ingredientsRequired': 'लागणारे साहित्य',
    'aware.stepByStep': 'कृती पद्धती',
    'aware.keyBenefits': 'महत्त्वाचे फायदे',
    'aware.precautions': 'महत्त्वाची काळजी',

    // Soil Scanner
    'soil.scannerTitle': 'माती व पाणी AI फोटो डिटेक्टर',
    'soil.scannerSub': 'मातीचा फोटो अपलोड करून त्वरित AI विश्लेषण व उपाय मिळवा.',
    'soil.tabSoil': '🌱 माती स्कॅनर',
    'soil.tabWater': '💧 जलस्रोत स्कॅनर',
    'soil.uploadTitle': 'फोटो अपलोड करा',
    'soil.uploadSub': 'दिवसाच्या प्रकाशात काढलेला फोटो द्या.',
    'soil.btnScan': 'AI विश्लेषण करा',
    'soil.healthIndex': 'माती आरोग्य निर्देशांक',
    'soil.moistureLevel': 'ओलाव्याची पातळी',
    'soil.organicMatter': 'सेंद्रिय घटक',
    'soil.recommendations': 'तातडीचे उपाय',

    // Pollution
    'poll.title': 'प्रदूषण तक्रार निवारण पोर्टल',
    'poll.sub': 'प्रदूषणाची तक्रार नोंदवा व AI प्रतिबंधक उपाय मिळवा.',
    'poll.btnFile': 'नवीन तक्रार करा',
    'poll.btnTrack': 'तक्रारीची स्थिती तपासा',
    'poll.domainLand': 'जमीन प्रदूषण',
    'poll.domainWater': 'जल प्रदूषण',

    // Footer
    'footer.brand': 'इडन सिंक रिव्हायव्हल',
    'footer.sub': 'जमीन व जलस्रोत पुनरुज्जीवन मंच',
    'footer.helplineLabel': 'हेल्पलाइन क्रमांक:',
    'footer.quote': '"पृथ्वी वाचवूया, निसर्गाशी जोडूया."',
    'footer.copyright': '© २०२६ इडन सिंक रिव्हायव्हल.',
  },
  gu: {
    // Nav
    'nav.brand': 'ઈડન સિંક',
    'nav.revival': 'પુનરુત્થાન',
    'nav.tagline': 'જમીન અને જળાશય પુનર્જીવન',
    'nav.home': 'હોમ',
    'nav.soilScanner': 'જમીન AI સ્કેનર',
    'nav.pollution': 'પ્રદૂષણ ફરિયાદ',
    'nav.customers': 'ગ્રાહક ડેટાબેઝ',
    'nav.elnino': 'અલ નીનો અને આબોહવા',
    'nav.govt': 'સરકારી યોજનાઓ',
    'nav.register': 'નોંધણી',
    'nav.awareness': 'માર્ગદર્શિકા',
    'nav.portal': 'પોર્ટલ',
    'nav.admin': 'એડમિન',
    'nav.login': 'લૉગિન / બદલો',
    'nav.logout': 'લૉગઆઉટ',
    'nav.call': 'કૉલ કરો:',
    'nav.landowner': 'જમીનદાર',
    'nav.adminUser': 'એડમિન',

    // Hero
    'hero.badge': 'ઈડન સિંક રિવાઇવલ — જમીન અને જળાશય પુનર્જીવન ઇકોસિસ્ટમ',
    'hero.helpline': 'ઇમરજન્સી હેલ્પલાઇન:',
    'hero.title1': 'ઈડન સિંક રિવાઇવલ:',
    'hero.title2': 'જમીન અને જળાશય પુનર્જીવન',
    'hero.subtitle': 'તમારી ખેતીની જમીન, બંજર જમીન, તળાવ અથવા કૂવાને પુનર્જીવિત કરવા માટે નોંધણી કરો અથવા પ્રદૂષણ સામે ફરિયાદ કરો.',
    'hero.btnRegister': 'જમીન / જળાશય નોંધાવો',
    'hero.btnReportPollution': 'પ્રદૂષણની ફરિયાદ કરો',
    'hero.btnGovt': 'સરકારી યોજનાઓ',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'એકર જમીન પુનર્જીવિત',
    'hero.stat1Sub': 'સેન્દ્રીય કાર્બન વૃદ્ધિ',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'તળાવોની સફાઈ',
    'hero.stat2Sub': 'ભૂગર્ભજળ રિચાર્જ',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'પ્રદૂષણ ફરિયાદોનું નિરાકરણ',
    'hero.stat3Sub': 'રાસાયણિક કચરા મુક્તિ',
    'hero.stat4Val': '₹48.2 કરોડ',
    'hero.stat4Title': 'સરકારી સબસિડી',
    'hero.stat4Sub': 'ખેડૂતોને સીધો લાભ',

    // Home Features
    'home.pillarsTitle': 'પુનર્જીવન અને ઉપાયો',
    'home.pillarsHeader': 'ઈડન સિંક: જમીન અને જળ સંરક્ષણ મંચ',
    'home.pillarsSub': 'ખેડૂત નોંધણી, પ્રદૂષણ ફરિયાદ, આબોહવાની માહિતી અને સરકારી સહાયનું એકીકરણ.',
    'home.soilCardTitle': 'જમીન AI ફોટો સ્કેનર',
    'home.soilCardBadge': 'સૂકી • ચીકણી • ફળદ્રુપ • ભેજવાળી',
    'home.soilCardDesc': 'ખેતરની માટીનો ફોટો પાડો. AI તરત જ માટીનો પ્રકાર ઓળખી કુદરતી ખાતરની સલાહ આપશે.',
    'home.soilCardBtn': 'માટીનો ફોટો સ્કેન કરો',
    'home.pollCardTitle': 'જમીન અને જળ પ્રદૂષણ ફરિયાદ',
    'home.pollCardBadge': 'AI ત્વરિત ઉકેલ સક્રિય',
    'home.pollCardDesc': 'રાસાયણિક કચરો, ગટરનું પાણી અથવા પ્લાસ્ટિક કચરા સામે ફરિયાદ નોંધાવો.',
    'home.pollCardBtn': 'ફરિયાદ કરો / ટ્રેક કરો',
    'home.custCardTitle': 'ગ્રાહક ડેટાબેઝ',
    'home.custCardBadge': 'ફક્ત એડમિન માટે',
    'home.custCardDesc': 'ખેડૂતોની જમીન સ્વાસ્થ્ય માહિતી અને પુનર્જીવન યોજનાઓ.',
    'home.custCardBtn': 'ડેટાબેઝ જુઓ',
    'home.custCardBtnLogin': 'એડમિન લૉગિન',
    'home.elninoCardTitle': 'અલ નીનો અને આબોહવા',
    'home.elninoCardDesc': 'તાપમાનમાં ફેરફાર, વરસાદની આગાહી અને દુષ્કાળ સામે રક્ષણ.',
    'home.elninoCardBtn': 'આબોહવા કેન્દ્ર જુઓ',
    'home.agriCardTitle': 'ખેતી જમીન પુનર્જીવન',
    'home.agriCardDesc': 'બંજર જમીનને કુદરતી ખાતરો દ્વારા ફળદ્રુપ બનાવો.',
    'home.agriCardBtn': 'જમીન નોંધણી કરો',
    'home.waterCardTitle': 'જળાશય પુનર્જીવન',
    'home.waterCardDesc': 'તળાવમાંથી કાંપ કાઢવો, વાળા ઘાસ રોપવું અને જળ સંચય.',
    'home.waterCardBtn': 'યોજનાઓ જુઓ',
    'home.guideCardTitle': 'કુદરતી ખાતર માર્ગદર્શિકા',
    'home.guideCardDesc': '૨૦ કુદરતી ખાતર બનાવવાની રીતો, કાંપ સફાઈ અને કાયદા.',
    'home.guideCardBtn': 'માહિતી વાંચો',
    'home.helpBannerTitle': 'મદદ જોઈએ છે?',
    'home.helpBannerSub': 'ખેડૂત સહાયતા હેલ્પલાઇન',
    'home.helpBannerDesc': 'જમીન નોંધણી, માટી પરીક્ષણ અને પ્રદૂષણ નિવારણ માટે અમારી ટીમ હાજર છે.',

    // Awareness
    'aware.badge': 'ઈડન સિંક પર્યાવરણ જ્ઞાન અને ખેડૂત સશક્તિકરણ કેન્દ્ર',
    'aware.title': 'માટી, પાણી અને કુદરતી ખેતીનું વિજ્ઞાન',
    'aware.subtitle': 'નાના ખેડૂતો માટે ૨૦ કુદરતી ખાતર બનાવવાની રીતો, તળાવ સફાઈ અને કાર્બન વધારવાની માહિતી.',
    'aware.tabGuides': 'માર્ગદર્શિકાઓ',
    'aware.tabRecipes': '૨૦ કુદરતી ખાતર બનાવવાની રીતો',
    'aware.tabCalc': 'ઇકો કેલ્ક્યુલેટર',
    'aware.tabMyths': 'માન્યતા વિરુદ્ધ વિજ્ઞાન',
    'aware.tabBiofence': 'બાયો-ફેન્સિંગ યોજના',
    'aware.smallFarmerBadge': 'નાના ખેડૂતો માટે વિશેષ (૦.૫ થી ૩ એકર)',
    'aware.allCategories': 'બધી શ્રેણીઓ',
    'aware.searchPlaceholder': 'જીવામૃત, કુદરતી ખાતર, ક્વાથ શોધો...',
    'aware.prepTime': 'બનાવવાનો સમય',
    'aware.shelfLife': 'વાપરવાનો સમયગાળો',
    'aware.dilution': 'મિશ્રણનું પ્રમાણ',
    'aware.costEst': 'અંદાજિત ખર્ચ',
    'aware.viewRecipeBtn': 'બનાવવાની રીત જુઓ',
    'aware.ingredientsRequired': 'જરૂરી સામગ્રી',
    'aware.stepByStep': 'તબક્કાવાર પદ્ધતિ',
    'aware.keyBenefits': 'મુખ્ય ફાયદાઓ',
    'aware.precautions': 'મહત્વની સાવચેતી',

    // Soil Scanner
    'soil.scannerTitle': 'માટી અને જળ AI ફોટો ડિટેક્ટર',
    'soil.scannerSub': 'માટીનો ફોટો અપલોડ કરી તરત AI વિશ્લેષણ મેળવો.',
    'soil.tabSoil': '🌱 માટી સ્કેનર',
    'soil.tabWater': '💧 જળાશય સ્કેનર',
    'soil.uploadTitle': 'ફોટો અપલોડ કરો',
    'soil.uploadSub': 'કુદરતી પ્રકાશમાં લીધેલો ફોટો વાપરો.',
    'soil.btnScan': 'AI વિશ્લેષણ કરો',
    'soil.healthIndex': 'માટી સ્વાસ્થ્ય સૂચકાંક',
    'soil.moistureLevel': 'ભેજનું પ્રમાણ',
    'soil.organicMatter': 'સેન્દ્રીય પદાર્થ',
    'soil.recommendations': 'તાત્કાલિક પગલાં',

    // Pollution
    'poll.title': 'પ્રદૂષણ ફરિયાદ નિવારણ પોર્ટલ',
    'poll.sub': 'પ્રદૂષણની ફરિયાદ કરો અને તાત્કાલિક ઉકેલ મેળવો.',
    'poll.btnFile': 'નવી ફરિયાદ કરો',
    'poll.btnTrack': 'ફરિયાદ સ્થિતિ જુઓ',
    'poll.domainLand': 'જમીન પ્રદૂષણ',
    'poll.domainWater': 'જળ પ્રદૂષણ',

    // Footer
    'footer.brand': 'ઈડન સિંક રિવાઇવલ',
    'footer.sub': 'જમીન અને જળાશય પુનર્જીવન પ્લેટફોર્મ',
    'footer.helplineLabel': 'હેલ્પલાઇન નંબર:',
    'footer.quote': '"ધરતી બચાવો, પ્રકૃતિ સાથે જીવો."',
    'footer.copyright': '© ૨૦૨૬ ઈડન સિંક રિવાઇવલ.',
  },
  pa: {
    // Nav
    'nav.brand': 'ਈਡਨ ਸਿੰਕ',
    'nav.revival': 'ਮੁੜ ਸੁਰਜੀਤੀ',
    'nav.tagline': 'ਜ਼ਮੀਨ ਅਤੇ ਜਲ ਸਰੋਤ ਬਹਾਲੀ',
    'nav.home': 'ਮੁੱਖ ਪੰਨਾ',
    'nav.soilScanner': 'ਮਿੱਟੀ AI ਸਕੈਨਰ',
    'nav.pollution': 'ਪ੍ਰਦੂਸ਼ਣ ਸ਼ਿਕਾਇਤਾਂ',
    'nav.customers': 'ਗਾਹਕ ਡਾਟਾਬੇਸ',
    'nav.elnino': 'ਅਲ ਨੀਨੋ ਅਤੇ ਮੌਸਮ',
    'nav.govt': 'ਸਰਕਾਰੀ ਪ੍ਰੋਜੈਕਟ',
    'nav.register': 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    'nav.awareness': 'ਜਾਗਰੂਕਤਾ ਤੇ ਗਾਈਡਾਂ',
    'nav.portal': 'ਪੋਰਟਲ',
    'nav.admin': 'ਐਡਮਿਨ',
    'nav.login': 'ਲਾਗਇਨ / ਬਦਲੋ',
    'nav.logout': 'ਲਾਗਆਉਟ',
    'nav.call': 'ਕਾਲ ਕਰੋ:',
    'nav.landowner': 'ਜ਼ਮੀਨ ਮਾਲਕ',
    'nav.adminUser': 'ਐਡਮਿਨ',

    // Hero
    'hero.badge': 'ਈਡਨ ਸਿੰਕ ਰਿਵਾਈਵਲ — ਜ਼ਮੀਨ ਅਤੇ ਜਲ ਸਰੋਤ ਬਹਾਲੀ ਵਾਤਾਵਰਣ',
    'hero.helpline': 'ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ:',
    'hero.title1': 'ਈਡਨ ਸਿੰਕ ਰਿਵਾਈਵਲ:',
    'hero.title2': 'ਜ਼ਮੀਨ ਅਤੇ ਜਲ ਸਰੋਤ ਬਹਾਲੀ',
    'hero.subtitle': 'ਆਪਣੀ ਖੇਤੀਯੋਗ ਜ਼ਮੀਨ, ਬੰਜਰ ਮਿੱਟੀ, ਛੱਪੜ ਜਾਂ ਝੀਲ ਦੀ ਬਹਾਲੀ ਲਈ ਰਜਿਸਟਰ ਕਰੋ ਜਾਂ ਕੈਮੀਕਲ ਪ੍ਰਦੂਸ਼ਣ ਖਿਲਾਫ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ।',
    'hero.btnRegister': 'ਜ਼ਮੀਨ / ਜਲ ਸਰੋਤ ਰਜਿਸਟਰ ਕਰੋ',
    'hero.btnReportPollution': 'ਪ੍ਰਦੂਸ਼ਣ ਦੀ ਸ਼ਿਕਾਇਤ ਕਰੋ',
    'hero.btnGovt': 'ਸਰਕਾਰੀ ਸਕੀਮਾਂ',
    'hero.stat1Val': '14,280+',
    'hero.stat1Title': 'ਏਕੜ ਜ਼ਮੀਨ ਬਹਾਲ',
    'hero.stat1Sub': 'ਜੈਵਿਕ ਕਾਰਬਨ ਵਾਧਾ',
    'hero.stat2Val': '890+',
    'hero.stat2Title': 'ਛੱਪੜਾਂ ਦੀ ਸਫਾਈ',
    'hero.stat2Sub': 'ਧਰਤੀ ਹੇਠਲਾ ਪਾਣੀ ਰੀਚਾਰਜ',
    'hero.stat3Val': '1,450+',
    'hero.stat3Title': 'ਪ੍ਰਦੂਸ਼ਣ ਸ਼ਿਕਾਇਤਾਂ ਦਾ ਹੱਲ',
    'hero.stat3Sub': 'ਜ਼ਹਿਰੀਲੇ ਕੂੜੇ ਤੋਂ ਮੁਕਤੀ',
    'hero.stat4Val': '₹48.2 ਕਰੋੜ',
    'hero.stat4Title': 'ਸਰਕਾਰੀ ਸਬਸਿਡੀ',
    'hero.stat4Sub': 'ਕਿਸਾਨਾਂ ਨੂੰ ਸਿੱਧੀ ਸਹਾਇਤਾ',

    // Home Features
    'home.pillarsTitle': 'ਬਹਾਲੀ ਅਤੇ ਹੱਲ',
    'home.pillarsHeader': 'ਈਡਨ ਸਿੰਕ: ਜ਼ਮੀਨ ਅਤੇ ਪਾਣੀ ਸੰਭਾਲ ਦਾ ਡਿਜੀਟਲ ਪਲੇਟਫਾਰਮ',
    'home.pillarsSub': 'ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ, ਪ੍ਰਦੂਸ਼ਣ ਨਿਵਾਰਣ, ਮੌਸਮ ਜਾਣਕਾਰੀ ਅਤੇ ਸਰਕਾਰੀ ਫੰਡਾਂ ਦਾ ਤਾਲਮੇਲ।',
    'home.soilCardTitle': 'ਮਿੱਟੀ AI ਫੋਟੋ ਸਕੈਨਰ',
    'home.soilCardBadge': 'ਸੁੱਕੀ • ਚੀਕਣੀ • ਉਪਜਾਊ • ਨਮੀ ਵਾਲੀ',
    'home.soilCardDesc': 'ਆਪਣੇ ਖੇਤ ਦੀ ਮਿੱਟੀ ਦੀ ਫੋਟੋ ਲਓ। AI ਤੁਰੰਤ ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਪਛਾਣ ਕੇ ਕੁਦਰਤੀ ਖਾਦ ਦੀ ਸਲਾਹ ਦੇਵੇਗਾ।',
    'home.soilCardBtn': 'ਮਿੱਟੀ ਦੀ ਫੋਟੋ ਸਕੈਨ ਕਰੋ',
    'home.pollCardTitle': 'ਜ਼ਮੀਨ ਅਤੇ ਪਾਣੀ ਪ੍ਰਦੂਸ਼ਣ ਸ਼ਿਕਾਇਤਾਂ',
    'home.pollCardBadge': 'AI ਤੁਰੰਤ ਹੱਲ ਸਰਗਰਮ',
    'home.pollCardDesc': 'ਰਸਾਇਣਕ ਕੂੜਾ, ਗੰਦਾ ਪਾਣੀ ਜਾਂ ਪਲਾਸਟਿਕ ਸੁੱਟਣ ਖਿਲਾਫ ਸ਼ਿਕਾਇਤ ਕਰੋ।',
    'home.pollCardBtn': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ / ਟਰੈਕ ਕਰੋ',
    'home.custCardTitle': 'ਗਾਹਕ ਡਾਟਾਬੇਸ',
    'home.custCardBadge': 'ਸਿਰਫ਼ ਐਡਮਿਨ ਲਈ',
    'home.custCardDesc': 'ਕਿਸਾਨਾਂ ਦੀ ਜ਼ਮੀਨ ਦੀ ਸਿਹਤ ਅਤੇ ਬਹਾਲੀ ਯੋਜਨਾਵਾਂ ਦਾ ਰਿਕਾਰਡ।',
    'home.custCardBtn': 'ਡਾਟਾਬੇਸ ਦੇਖੋ',
    'home.custCardBtnLogin': 'ਐਡਮਿਨ ਲਾਗਇਨ',
    'home.elninoCardTitle': 'ਅਲ ਨੀਨੋ ਅਤੇ ਮੌਸਮ',
    'home.elninoCardDesc': 'ਤਾਪਮਾਨ ਬਦਲਾਅ, ਮੀਂਹ ਦਾ ਅੰਦਾਜ਼ਾ ਅਤੇ ਸੋਕੇ ਤੋਂ ਬਚਾਅ ਦੇ ਤਰੀਕੇ।',
    'home.elninoCardBtn': 'ਮੌਸਮ ਕੇਂਦਰ ਦੇਖੋ',
    'home.agriCardTitle': 'ਖੇਤੀਬਾੜੀ ਜ਼ਮੀਨ ਬਹਾਲੀ',
    'home.agriCardDesc': 'ਬੰਜਰ ਜਾਂ ਕੱਲਰ ਜ਼ਮੀਨ ਨੂੰ ਹਰੀ ਖਾਦ ਅਤੇ ਜੈਵਿਕ ਤਰੀਕਿਆਂ ਨਾਲ ਉਪਜਾਊ ਬਣਾਓ।',
    'home.agriCardBtn': 'ਜ਼ਮੀਨ ਰਜਿਸਟਰ ਕਰੋ',
    'home.waterCardTitle': 'ਜਲ ਸਰੋਤਾਂ ਦੀ ਬਹਾਲੀ',
    'home.waterCardDesc': 'ਛੱਪੜਾਂ ਦੀ ਗਾਦ ਕੱਢਣਾ, ਖਸ ਘਾਹ ਲਗਾਉਣਾ ਅਤੇ ਮੀਂਹ ਦਾ ਪਾਣੀ ਸਾਂਭਣਾ।',
    'home.waterCardBtn': 'ਸਕੀਮਾਂ ਦੇਖੋ',
    'home.guideCardTitle': 'ਕੁਦਰਤੀ ਖਾਦ ਗਾਈਡ',
    'home.guideCardDesc': '20 ਕੁਦਰਤੀ ਖਾਦਾਂ ਬਣਾਉਣ ਦੇ ਤਰੀਕੇ, ਗਾਦ ਕੱਢਣਾ ਅਤੇ ਕਾਨੂੰਨ।',
    'home.guideCardBtn': 'ਜਾਣਕਾਰੀ ਪੜ੍ਹੋ',
    'home.helpBannerTitle': 'ਕੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'home.helpBannerSub': 'ਕਿਸਾਨ ਸਹਾਇਤਾ ਹੈਲਪਲਾਈਨ',
    'home.helpBannerDesc': 'ਜ਼ਮੀਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ, ਮਿੱਟੀ ਪਰਖ ਅਤੇ ਪ੍ਰਦੂਸ਼ਣ ਹੱਲ ਲਈ ਸਾਡੀ ਟੀਮ ਹਾਜ਼ਰ ਹੈ।',

    // Awareness
    'aware.badge': 'ਈਡਨ ਸਿੰਕ ਵਾਤਾਵਰਣ ਗਿਆਨ ਅਤੇ ਕਿਸਾਨ ਸਸ਼ਕਤੀਕਰਨ ਕੇਂਦਰ',
    'aware.title': 'ਮਿੱਟੀ, ਪਾਣੀ ਅਤੇ ਕੁਦਰਤੀ ਖੇਤੀ ਦਾ ਵਿਗਿਆਨ',
    'aware.subtitle': 'ਛੋਟੇ ਅਤੇ ਨਵੇਂ ਕਿਸਾਨਾਂ ਲਈ 20 ਕੁਦਰਤੀ ਖਾਦਾਂ ਬਣਾਉਣ ਦੇ ਤਰੀਕੇ, ਛੱਪੜ ਸਫਾਈ ਅਤੇ ਜੈਵਿਕ ਕਾਰਬਨ ਵਧਾਉਣ ਦੀ ਜਾਣਕਾਰੀ।',
    'aware.tabGuides': 'ਤਸਵੀਰਾਂ ਸਮੇਤ ਗਾਈਡਾਂ',
    'aware.tabRecipes': '20 ਕੁਦਰਤੀ ਖਾਦਾਂ ਬਣਾਉਣ ਦੇ ਤਰੀਕੇ',
    'aware.tabCalc': 'ਈਕੋ ਕੈਲਕੁਲੇਟਰ',
    'aware.tabMyths': 'ਵਹਿਮ ਬਨਾਮ ਵਿਗਿਆਨ',
    'aware.tabBiofence': 'ਬਾਇਓ-ਫੈਂਸਿੰਗ ਯੋਜਨਾ',
    'aware.smallFarmerBadge': 'ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਵਿਸ਼ੇਸ਼ (0.5 ਤੋਂ 3 ਏਕੜ)',
    'aware.allCategories': 'ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    'aware.searchPlaceholder': 'ਜੀਵਾਮ੍ਰਿਤ, ਕੁਦਰਤੀ ਖਾਦ, ਕੀਟਨਾਸ਼ਕ ਲੱਭੋ...',
    'aware.prepTime': 'ਤਿਆਰ ਕਰਨ ਦਾ ਸਮਾਂ',
    'aware.shelfLife': 'ਵਰਤੋਂ ਦੀ ਮਿਆਦ',
    'aware.dilution': 'ਘੋਲ ਦਾ ਅਨੁਪਾਤ',
    'aware.costEst': 'ਅੰਦਾਜ਼ਨ ਖਰਚਾ',
    'aware.viewRecipeBtn': 'ਤਰੀਕਾ ਦੇਖੋ',
    'aware.ingredientsRequired': 'ਲੋੜੀਂਦਾ ਸਾਮਾਨ',
    'aware.stepByStep': 'ਤਿਆਰ ਕਰਨ ਦਾ ਤਰੀਕਾ',
    'aware.keyBenefits': 'ਮੁੱਖ ਲਾਭ',
    'aware.precautions': 'ਜ਼ਰੂਰੀ ਸਾਵਧਾਨੀਆਂ',

    // Soil Scanner
    'soil.scannerTitle': 'ਮਿੱਟੀ ਅਤੇ ਪਾਣੀ AI ਫੋਟੋ ਡਿਟੈਕਟਰ',
    'soil.scannerSub': 'ਮਿੱਟੀ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰਕੇ ਤੁਰੰਤ AI ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਹੱਲ ਪ੍ਰਾਪਤ ਕਰੋ।',
    'soil.tabSoil': '🌱 ਮਿੱਟੀ ਸਕੈਨਰ',
    'soil.tabWater': '💧 ਜਲ ਸਰੋਤ ਸਕੈਨਰ',
    'soil.uploadTitle': 'ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
    'soil.uploadSub': 'ਕੁਦਰਤੀ ਰੌਸ਼ਨੀ ਵਿੱਚ ਖਿੱਚੀ ਫੋਟੋ ਵਰਤੋ।',
    'soil.btnScan': 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    'soil.healthIndex': 'ਮਿੱਟੀ ਸਿਹਤ ਸੂਚਕਾਂਕ',
    'soil.moistureLevel': 'ਨਮੀ ਦਾ ਪੱਧਰ',
    'soil.organicMatter': 'ਜੈਵਿਕ ਤੱਤ',
    'soil.recommendations': 'ਜ਼ਰੂਰੀ ਕਦਮ',

    // Pollution
    'poll.title': 'ਪ੍ਰਦੂਸ਼ਣ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਣ ਪੋਰਟਲ',
    'poll.sub': 'ਪ੍ਰਦੂਸ਼ਣ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਤੁਰੰਤ AI ਰੋਕਥਾਮ ਸਲਾਹ ਪਾਓ।',
    'poll.btnFile': 'ਨਵੀਂ ਸ਼ਿਕਾਇਤ ਕਰੋ',
    'poll.btnTrack': 'ਸ਼ਿਕਾਇਤ ਦੀ ਸਥਿਤੀ ਦੇਖੋ',
    'poll.domainLand': 'ਜ਼ਮੀਨ ਪ੍ਰਦੂਸ਼ਣ',
    'poll.domainWater': 'ਪਾਣੀ ਪ੍ਰਦੂਸ਼ਣ',

    // Footer
    'footer.brand': 'ਈਡਨ ਸਿੰਕ ਰਿਵਾਈਵਲ',
    'footer.sub': 'ਜ਼ਮੀਨ ਅਤੇ ਜਲ ਸਰੋਤ ਬਹਾਲੀ ਪਲੇਟਫਾਰਮ',
    'footer.helplineLabel': 'ਹੈਲਪਲਾਈਨ ਨੰਬਰ:',
    'footer.quote': '"ਧਰਤੀ ਬਚਾਓ, ਕੁਦਰਤ ਨਾਲ ਜੁੜੋ।"',
    'footer.copyright': '© 2026 ਈਡਨ ਸਿੰਕ ਰਿਵਾਈਵਲ।',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem('eden_sync_language') as SupportedLanguage;
      if (saved && APP_TRANSLATIONS[saved]) {
        return saved;
      }
    } catch {
      // ignore
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('eden_sync_language', lang);
    } catch {
      // ignore
    }
  };

  const KEY_ALIASES: Record<string, string> = {
    hero_title: 'hero.title1',
    hero_subtitle: 'hero.title2',
    hero_desc: 'hero.subtitle',
    hero_cta_register: 'hero.btnRegister',
    hero_cta_pollution: 'hero.btnReportPollution',
    hero_cta_govt: 'hero.btnGovt',
    stat_land_restored: 'hero.stat1Title',
    stat_water_rejuvenated: 'hero.stat2Title',
    stat_active_projects: 'hero.stat3Title',
    stat_farmers_supported: 'hero.stat4Title',
    nav_home: 'nav.home',
    nav_soil_scan: 'nav.soilScanner',
    nav_grievances: 'nav.pollution',
    nav_customers: 'nav.customers',
    nav_elnino: 'nav.elnino',
    nav_govt: 'nav.govt',
    nav_register: 'nav.register',
    nav_awareness: 'nav.awareness',
    nav_portal: 'nav.portal',
    nav_admin: 'nav.admin',
    nav_login: 'nav.login',
    nav_logout: 'nav.logout',
  };

  const t = (key: string, fallback?: string): string => {
    const targetKey = KEY_ALIASES[key] || key;
    const langDict = APP_TRANSLATIONS[language];
    if (langDict && langDict[targetKey]) {
      return langDict[targetKey];
    }
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (APP_TRANSLATIONS.en && APP_TRANSLATIONS.en[targetKey]) {
      return APP_TRANSLATIONS.en[targetKey];
    }
    if (APP_TRANSLATIONS.en && APP_TRANSLATIONS.en[key]) {
      return APP_TRANSLATIONS.en[key];
    }
    return fallback || (targetKey.includes('.') ? targetKey.split('.').pop() || key : key);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        languages: SUPPORTED_LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      setLanguage: () => {},
      t: (key: string, fallback?: string) => fallback || key,
      languages: SUPPORTED_LANGUAGES,
    };
  }
  return context;
};
